// ===== B2 Theme Data – Deutsch + Arabisch =====
const THEMES = [
  {id:1,icon:"🏫",
    titleDe:"Kinderuniversität",titleAr:"جامعة الأطفال",
    textDe:"Lernen in den Schulferien – seit 2002 bietet die Universität Tübingen Vorlesungen für Kinder an. Ohne Notendruck und freiwillig. Es gibt Kritik: Bewegungsmangel und nur für leistungsstarke Schüler geeignet.",
    textAr:"التعلم في العطل المدرسية – منذ 2002 تقدم جامعة توبنغن محاضرات للأطفال. بدون ضغط الدرجات واختياري. هناك انتقادات: قلة الحركة ومناسبة فقط للتلاميذ المتفوقين.",
    proDe:["Fördert Wissbegierde und Neugier","Macht Wissenschaft erlebbar","Ohne Schuldruck und Noten","Fördert selbstständiges Denken"],
    proAr:["يشجع حب المعرفة والفضول","يجعل العلوم قابلة للتجربة","بدون ضغط المدرسة والدرجات","يقوي التفكير المستقل"],
    contraDe:["Bewegungsmangel","Nur für leistungsstarke Schüler","Zusätzlicher Druck auf Kinder","Kosten für Eltern"],
    contraAr:["قلة النشاط الرياضي","مناسب فقط للتلاميذ المتفوقين","ضغط إضافي على الأطفال","تكاليف على الآباء"],
    vocab:[{de:"die Lehrveranstaltung",ar:"محاضرة / درس جامعي"},{de:"freiwillig",ar:"اختياري / تطوعي"},{de:"der Wissensdurst",ar:"التعطش للمعرفة"},{de:"der Befürworter",ar:"المؤيد"},{de:"der Gegner",ar:"المعارض"},{de:"die Kinderuniversität",ar:"جامعة الأطفال"},{de:"der Hörsaal",ar:"قاعة المحاضرات"},{de:"kritische Stimmen",ar:"أصوات ناقدة"},{de:"innovativ",ar:"مبتكر"}],
    phrasesDe:["Meiner Meinung nach ist die Kinderuniversität eine gute Idee, weil...","Einerseits fördert sie die Neugier, andererseits fehlt Bewegung.","Kritiker sagen, dass nicht alle Kinder profitieren."],
    phrasesAr:["في رأيي جامعة الأطفال فكرة جيدة لأن...","من ناحية تشجع الفضول، ومن ناحية أخرى تفتقر للحركة.","النقاد يقولون إن ليس كل الأطفال يستفيدون."],
    problem:{titleDe:"Organisation eines multikulturellen Sportfestes",titleAr:"تنظيم مهرجان رياضي متعدد الثقافات",textDe:"Sie sollen ein multikulturelles Sportfest in Ihrer Stadt organisieren. Was können Sie tun?",textAr:"يجب عليك تنظيم مهرجان رياضي متعدد الثقافات في مدينتك. ماذا يمكنك أن تفعل؟"},
    problemIdeasDe:["Sportarten aus aller Welt anbieten","Musik und Essen aus verschiedenen Kulturen","Gemischte Teams bilden","Informationsstände über verschiedene Länder","Preise für die Gewinner besorgen","Mehrsprachig werben"],
    problemIdeasAr:["تقديم رياضات مختلفة من جميع أنحاء العالم","موسيقى وأكل من ثقافات مختلفة","تكوين فرق مختلطة","أكشاك معلومات عن البلدان المختلفة","شراء جوائز للفائزين","إعلان بعدة لغات"]},
  {id:2,icon:"🏠",
    titleDe:"Wohnen im Alter in einer WG",titleAr:"العيش المشترك في الكبر (WG)",
    textDe:"Leben in einer Wohngemeinschaft im Alter – selbstständig in Gemeinschaft leben, der Einsamkeit entfliehen, mit professioneller Pflege. Kritiker befürchten die Unterbringung alter Menschen in WGs aus Kostengründen.",
    textAr:"العيش في شقة مشتركة في الكبر – حياة مستقلة في مجتمع، الهروب من الوحدة، مع الحصول على رعاية مهنية. النقاد يخافون من إيداع المسنين في WGs لأسباب مالية.",
    proDe:["Selbstständiges Leben in Gemeinschaft","Gegen Einsamkeit im Alter","Professionelle Unterstützung möglich","Günstiger als Pflegeheim"],
    proAr:["حياة مستقلة في مجتمع","ضد الوحدة في الكبر","دعم مهني ممكن","أرخص من دار المسنين"],
    contraDe:["Mögliche Konflikte in der WG","Nicht für Pflegefälle geeignet","Abhängig von externer Pflege","Idealisierte Vorstellung vom Alter"],
    contraAr:["احتمال النزاعات في WG","غير مناسب للحالات الحرجة","يعتمد على الرعاية الخارجية","تصور مثالي للشيخوخة"],
    vocab:[{de:"die Wohngemeinschaft (WG)",ar:"شقة مشتركة / سكن مشترك"},{de:"die Pflege",ar:"الرعاية / التمريض"},{de:"selbstständig",ar:"مستقل"},{de:"die Einsamkeit",ar:"الوحدة"},{de:"die Selbstständigkeit",ar:"الاستقلالية"},{de:"ambulant",ar:"رعاية خارجية"},{de:"die Pflegekraft",ar:"مقدم الرعاية"},{de:"die Kostengründe",ar:"أسباب مالية"}],
    phrasesDe:["Ich finde, dass eine WG im Alter eine gute Alternative ist, weil...","Ein Vorteil ist die Gemeinschaft gegen die Einsamkeit.","Niemand sollte aus Kostengründen in eine WG gezwungen werden."],
    phrasesAr:["أرى أن العيش المشترك في الكبر بديل جيد لأن...","ميزة هي المجتمع ضد الوحدة.","يجب ألا يُجبر أحد على WG لأسباب مالية."],
    problem:{titleDe:"Organisation einer Buchmesse im Kulturzentrum",titleAr:"تنظيم معرض كتاب في مركز ثقافي",textDe:"In einem Kulturzentrum in Ihrer Stadt findet eine Buchmesse statt. Helfen Sie bei der Planung.",textAr:"في مركز ثقافي في مدينتك سيقام معرض كتاب. ساعد في التخطيط."},
    problemIdeasDe:["Datum und Ort festlegen","Verlage und Autoren einladen","Lesungen und Workshops organisieren","Werbematerial und Plakate gestalten","Ecke für lokale Autoren","Café und Leseecke einrichten"],
    problemIdeasAr:["تحديد التاريخ والمكان","دعوة دور النشر والكتّاب","تنظيم قراءات وورش عمل","تصميم مواد إعلامية وملصقات","ركن كتب لمؤلفين محليين","إعداد مقهى وركن للقراءة"]},
  {id:3,icon:"🍟",
    titleDe:"Fast Food macht süchtig",titleAr:"الوجبات السريعة تسبب الإدمان",
    textDe:"Amerikanische Forscher vergleichen übermäßigen Fast-Food-Konsum mit Drogensucht. Selbst elektrische Schocks konnten Ratten nicht vom Essen abhalten. Dasselbe Belohnungssystem im Gehirn.",
    textAr:"باحثون أمريكيون يقارنون الإفراط في الوجبات السريعة بإدمان المخدرات. حتى الصدمات الكهربائية لم تمنع الفئران من الأكل. نفس نظام المكافآت في الدماغ.",
    proDe:["Fast Food ist bequem und zeitsparend","Schmeckt vielen Menschen","Günstig und überall verfügbar","Mäßiger Konsum ist akzeptabel"],
    proAr:["الوجبات السريعة مريحة وتوفر الوقت","طعمها جيد لكثير من الناس","رخيصة ومتوفرة في كل مكان","الاستهلاك المعتدل مقبول"],
    contraDe:["Macht süchtig wie eine Droge","Führt zu Fettleibigkeit","Enthält ungesunde Fette und Zucker","Schadet langfristig der Gesundheit"],
    contraAr:["تسبب الإدمان مثل المخدرات","تؤدي إلى السمنة","تحتوي على دهون وسكر غير صحي","تضر بالصحة على المدى الطويل"],
    vocab:[{de:"süchtig machen",ar:"يسبب الإدمان"},{de:"das Fast Food",ar:"الوجبات السريعة"},{de:"das Belohnungssystem",ar:"نظام المكافآت"},{de:"übermäßiger Konsum",ar:"الاستهلاك المفرط"},{de:"die Fettleibigkeit",ar:"السمنة"},{de:"das Verlangen",ar:"الرغبة / الشهوة"},{de:"die Kalorien",ar:"السعرات الحرارية"},{de:"die Völlerei",ar:"الشراهة"}],
    phrasesDe:["Fast Food ist praktisch, aber auf Dauer ungesund.","Die Studie zeigt, dass Fast Food süchtig machen kann.","Aufklärung über gesunde Ernährung ist wichtig."],
    phrasesAr:["الوجبات السريعة عملية لكنها غير صحية على المدى الطويل.","الدراسة تظهر أن الوجبات السريعة تسبب الإدمان.","التوعية بالتغذية الصحية مهمة."],
    problem:{titleDe:"Überraschungsparty für die Lehrerin",titleAr:"تنظيم حفلة مفاجئة للمعلمة",textDe:"Die Teilnehmer Ihres Kurses möchten eine Überraschungsparty für ihre Lehrerin organisieren. Was können Sie tun?",textAr:"المشاركون في دورتك يريدون تنظيم حفلة مفاجئة لمعلمتهم. ماذا يمكنكم أن تفعلوا؟"},
    problemIdeasDe:["Datum und Ort geheim festlegen","Essen und Trinken planen","Dekoration und Musik organisieren","Geschenk für die Lehrerin besorgen","Rede oder Dankeskarte vorbereiten","Alle außer der Lehrerin informieren"],
    problemIdeasAr:["تحديد التاريخ والمكان سراً","تخطيط الطعام والشراب","تنظيم الديكور والموسيقى","شراء هدية للمعلمة","تحضير خطاب أو بطاقة شكر","إعلام الجميع باستثناء المعلمة"]},
  {id:4,icon:"🌎",
    titleDe:"Englisch als Unternehmenssprache",titleAr:"الإنجليزية كلغة شركات",
    textDe:"Für globale Unternehmen ist Englisch als Unternehmenssprache normal. Vorteile: leichtere Kommunikation, keine Übersetzungskosten. Nachteile: Mitarbeiter fühlen sich eingeschränkt, Verlust von Denkmustern.",
    textAr:"بالنسبة للشركات العالمية، الإنجليزية كلغة شركات أمر طبيعي. مزايا: تواصل أسهل، لا تكاليف ترجمة. عيوب: الموظفون يشعرون بالقيود، فقدان أنماط التفكير.",
    proDe:["Erleichtert internationale Kommunikation","Spart Übersetzungskosten","Fördert globale Teamarbeit","Ermöglicht globalen Austausch"],
    proAr:["يسهل التواصل الدولي","يوفر تكاليف المترجمين","يشجع بناء الفرق العالمية","يمكن التبادل العالمي"],
    contraDe:["Mitarbeiter fühlen sich unsicher","Eingeschränkter Wortschatz","Verschiedene Denkmuster gehen verloren","Akzente führen zu Missverständnissen"],
    contraAr:["الموظفون يشعرون بعدم الأمان","المفردات محدودة","أنماط التفكير المختلفة تضيع","اللهجات تسبب سوء الفهم"],
    vocab:[{de:"die Unternehmenssprache",ar:"لغة الشركات"},{de:"der Dolmetscher",ar:"المترجم الفوري"},{de:"die Übersetzung",ar:"الترجمة"},{de:"die Muttersprache",ar:"اللغة الأم"},{de:"der Wortschatz",ar:"المفردات"},{de:"der Akzent",ar:"اللهجة / اللكنة"},{de:"das Denkmuster",ar:"نمط التفكير"},{de:"die Sprachenvielfalt",ar:"تنوع اللغات"}],
    phrasesDe:["Englisch als Unternehmenssprache hat Vor- und Nachteile.","Einerseits wird die Kommunikation einfacher, andererseits fühlen sich Mitarbeiter unsicher.","Die Sprachenvielfalt sollte erhalten bleiben."],
    phrasesAr:["الإنجليزية كلغة شركات لها مزايا وعيوب.","من ناحية التواصل يصبح أسهل، ومن ناحية أخرى الموظفون يشعرون بعدم الأمان.","يجب الحفاظ على تنوع اللغات."],
    problem:{titleDe:"Buchpräsentation im Unterricht",titleAr:"تقديم كتاب في الفصل",textDe:"Sie sollen ein Buch im Unterricht präsentieren. Wie organisieren Sie die Präsentation?",textAr:"يجب عليكم تقديم كتاب في الفصل. كيف تنظمون العرض؟"},
    problemIdeasDe:["Ein Buch wählen, das alle interessiert","Präsentation in Kapitel aufteilen","Aufgaben verteilen: Inhalt, Interpretation, Hintergrund","Handouts vorbereiten","Auszug aus dem Buch vorlesen","Diskussionsfragen vorbereiten"],
    problemIdeasAr:["اختيار كتاب يهم الجميع","تقسيم العرض إلى فصول","توزيع المهام: المحتوى، التفسير، الخلفية","إعداد نشرات","قراءة مقطع من الكتاب","تحضير أسئلة للنقاش"]},
  {id:5,icon:"💰",
    titleDe:"Trinkgeld",titleAr:"إكرامية (بقشيش)",
    textDe:"Trinkgeld ist üblich im Restaurant, beim Friseur und im Taxi. Es gilt als Anerkennung für gute Dienstleistung. In manchen Berufen ist es Teil des Lohns. Es variiert von Land zu Land.",
    textAr:"الإكرامية معتادة في المطعم وعند الحلاق وفي التاكسي. تعتبر تقديراً للخدمة الجيدة. في بعض المهن هي جزء من الراتب. تختلف من بلد لآخر.",
    proDe:["Anerkennung für gute Dienstleistung","Motivation für Mitarbeiter","Teil des Lohns in manchen Berufen","Kleine Geste der Wertschätzung"],
    proAr:["تقدير للخدمة الجيدة","تحفيز للموظفين","جزء من الراتب في بعض المهن","لفتة صغيرة من التقدير"],
    contraDe:["Sollte nicht erwartet werden","Schlechter Service verdient keins","Nicht jeder kann es sich leisten","Verwirrung über den richtigen Betrag"],
    contraAr:["لا ينبغي أن تكون مفروضة","الخدمة السيئة لا تستحق","ليس كل شخص يستطيع دفعها","الارتباك حول المبلغ المناسب"],
    vocab:[{de:"das Trinkgeld",ar:"الإكرامية / البقشيش"},{de:"die Anerkennung",ar:"التقدير"},{de:"der Friseur",ar:"الحلاق"},{de:"die Bestechung",ar:"الرشوة"},{de:"der Lohn",ar:"الراتب"},{de:"die Großzügigkeit",ar:"الكرم"},{de:"die Gepflogenheit",ar:"العادة / التقليد"},{de:"die Unsicherheit",ar:"عدم اليقين"}],
    phrasesDe:["Ich gebe Trinkgeld, wenn der Service gut ist.","In Deutschland sind 5-10% üblich.","Trinkgeld sollte nicht erwartet werden."],
    phrasesAr:["أعطي إكرامية عندما تكون الخدمة جيدة.","في ألمانيا 5-10% معتادة.","لا ينبغي توقع الإكرامية."],
    problem:{titleDe:"Interview mit einem berühmten Sänger",titleAr:"مقابلة مغنٍ مشهور",textDe:"Als Journalist haben Sie die Chance, einen berühmten Sänger zu interviewen. Bereiten Sie eine Fragenliste vor.",textAr:"كصحفي لديك فرصة مقابلة مغنٍ مشهور. حضّر قائمة الأسئلة."},
    problemIdeasDe:["Den Sänger auswählen","Fragen zur Karriere vorbereiten","Fragen zum Privatleben (falls erlaubt)","Nach Inspiration und Vorbildern fragen","Nach aktuellen Projekten fragen","Fotos und Autogramme organisieren"],
    problemIdeasAr:["اختيار المغني","تحضير أسئلة عن المسيرة الفنية","أسئلة عن الحياة الشخصية (إن سُمح)","السؤال عن الإلهام والقدوات","الاستفسار عن المشاريع الحالية","تنظيم الصور والتوقيعات"]},
  {id:6,icon:"💓",
    titleDe:"Blutspende",titleAr:"التبرع بالدم",
    textDe:"15.000 Blutspenden werden täglich in Deutschland benötigt. Nur 3-5% der Bevölkerung spenden. Wer gesund ist (18-68 Jahre, mind. 50 kg) kann spenden. Es dauert 20-30 Minuten.",
    textAr:"15.000 تبرع بالدم مطلوبة يومياً في ألمانيا. فقط 3-5% من السكان يتبرعون. من كان بصحة جيدة (18-68 سنة، وزن 50 كغ على الأقل) يمكنه التبرع. يستغرق 20-30 دقيقة.",
    proDe:["Lebensrettende Hilfe","Kostenloser Gesundheitscheck","Gutes Gefühl, anderen zu helfen","Schnell und unkompliziert"],
    proAr:["مساعدة منقذة للحياة","فحص الدم مجاناً","شعور جيد بمساعدة الآخرين","سريع وغير معقد"],
    contraDe:["Angst vor Nadeln","Kann Müdigkeit verursachen","Nicht jeder kann spenden","Braucht Zeit und Anfahrtsweg"],
    contraAr:["الخوف من الإبر","قد يسبب التعب","ليس الجميع يستطيع التبرع","يحتاج وقتاً ووصلة إلى المركز"],
    vocab:[{de:"die Blutspende",ar:"التبرع بالدم"},{de:"der Blutkonservenmangel",ar:"نقص أكياس الدم"},{de:"die Blutentnahme",ar:"سحب الدم"},{de:"der Gesundheitscheck",ar:"الفحص الصحي"},{de:"die Spendetauglichkeit",ar:"الأهلية للتبرع"},{de:"die Erholungszeit",ar:"وقت الاستشفاء"},{de:"der Unfall",ar:"الحادث"}],
    phrasesDe:["Blutspenden rettet Leben.","Es dauert nur 20 Minuten und tut nicht weh.","Ich spende regelmäßig, weil ich helfen möchte."],
    phrasesAr:["التبرع بالدم ينقذ الأرواح.","يستغرق فقط 20 دقيقة ولا يؤلم.","أتبرع بانتظام لأنني أريد المساعدة."],
    problem:{titleDe:"Gesundheitstag organisieren",titleAr:"تنظيم يوم معلومات عن الصحة",textDe:"In einem Gesundheitszentrum in Ihrer Stadt findet ein Informationstag zum Thema Gesundheit statt.",textAr:"في مركز صحي في مدينتك سيقام يوم معلومات عن الصحة."},
    problemIdeasDe:["Vorträge über gesunde Ernährung","Blutdruck messen","Sportaktivitäten (Yoga, Spaziergang)","Ernährungsplan erstellen","Informationsmaterial gestalten","Ärzte und Experten einladen"],
    problemIdeasAr:["محاضرات عن التغذية الصحية","قياس ضغط الدم","أنشطة رياضية (يوجا، مشي)","إعداد برنامج غذائي","تصميم مواد إعلامية","دعوة أطباء وخبراء"]},
  {id:7,icon:"🚬",
    titleDe:"Rauchen aufhören",titleAr:"الإقلاع عن التدخين",
    textDe:"21 Millionen Raucher in Deutschland. Jugendliche fangen früh an. Gründe: Gruppendruck, Vorbilder in den Medien, Neugier, Protest. Die Zahl der rauchenden Mädchen steigt.",
    textAr:"21 مليون مدخن في ألمانيا. المراهقون يبدأون مبكراً. الأسباب: ضغط الأصدقاء، قدوات من الإعلام، الفضول، الاحتجاج. عدد الفتيات المدخنات يزداد.",
    proDe:["Baut kurzfristig Stress ab","Persönliche Entscheidung","Sozialer Faktor in Gruppen"],
    proAr:["يخفف التوتر على المدى القصير","قرار شخصي","عامل اجتماعي في المجموعات"],
    contraDe:["Sehr ungesund (Krebs, Herz)","Teuer auf lange Sicht","Passivrauchen schadet anderen","Macht süchtig"],
    contraAr:["غير صحي جداً (سرطان، قلب)","مكلف على المدى الطويل","التدخين السلبي يضر الآخرين","يسبب الإدمان"],
    vocab:[{de:"das Rauchen",ar:"التدخين"},{de:"die Zigarette",ar:"السجارة"},{de:"der Raucher",ar:"المدخن"},{de:"die Sucht",ar:"الإدمان"},{de:"der Gruppendruck",ar:"ضغط الأقران"},{de:"das Vorbild",ar:"القدوة"},{de:"die Neugier",ar:"الفضول"},{de:"die Werbung",ar:"الإعلانات"}],
    phrasesDe:["Rauchen ist sehr ungesund und macht süchtig.","Jugendliche fangen oft aus Neugier oder Gruppendruck an.","Aufklärung in Schulen ist sehr wichtig."],
    phrasesAr:["التدخين غير صحي جداً ويسبب الإدمان.","المراهقون يبدأون غالباً بسبب الفضول أو ضغط الأصدقاء.","التوعية في المدارس مهمة جداً."],
    problem:{titleDe:"Stadtrundfahrt für Schüler",titleAr:"جولة سياحية لطلاب في مدينتك",textDe:"Eine Schülergruppe besucht Ihre Stadt. Planen Sie ein Programm.",textAr:"مجموعة من الطلاب تزور مدينتك. خطط لبرنامج."},
    problemIdeasDe:["Sehenswürdigkeiten auswählen","Rundgang oder Busfahrt","Zeit zur freien Erkundung","Restaurant mit lokaler Küche","Kulturelle Highlights","Infomaterial in mehreren Sprachen"],
    problemIdeasAr:["اختيار المعالم السياحية","جولة سيراً أو بالحافلة","وقت للاستكشاف الذاتي","مطعم بالمأكولات المحلية","معالم ثقافية","مواد إعلامية بعدة لغات"]},
  {id:8,icon:"📺",
    titleDe:"Fernsehen macht Kinder dumm",titleAr:"التلفاز يجعل الأطفال أغبياء",
    textDe:"Studien zeigen: Wer in der Kindheit viel fernsieht, hat später schlechtere Schulabschlüsse. Fernsehen führt zu Bewegungsmangel und frühem Kontakt mit Alkohol. Maximal eine Stunde täglich wird empfohlen.",
    textAr:"الدراسات تظهر: من يشاهد التلفاز كثيراً في الطفولة يحصل على شهادات أقل لاحقاً. التلفاز يؤدي إلى الخمول والاتصال المبكر بالكحول. يُنصح بساعة واحدة يومياً كحد أقصى.",
    proDe:["Fernsehen kann unterhalten","Manche Sendungen sind lehrreich","Fördert Medienkompetenz"],
    proAr:["التلفاز يمكن أن يسلي","بعض البرامج تعليمية","يشجع الثقافة الإعلامية"],
    contraDe:["Zu viel Fernsehen macht passiv","Schlechtere schulische Leistungen","Fördert Bewegungsmangel","Früher Kontakt mit Tabak und Alkohol"],
    contraAr:["كثرة التلفاز تجعل الطفل سلبياً","نتائج مدرسية أسوأ","يشجع الخمول البدني","اتصال مبكر بالتبغ والكحول"],
    vocab:[{de:"der Fernsehkonsum",ar:"استهلاك التلفاز"},{de:"der Schulabschluss",ar:"الشهادة المدرسية"},{de:"die körperliche Inaktivität",ar:"الخمول البدني"},{de:"die Bildung",ar:"التعليم"},{de:"die Ablenkung",ar:"التشتت"},{de:"das Gehirn",ar:"الدماغ"}],
    phrasesDe:["Die Studien zeigen einen klaren Zusammenhang.","Eltern sollten den Fernsehkonsum kontrollieren.","Eine Stunde pro Tag ist akzeptabel."],
    phrasesAr:["الدراسات تظهر علاقة واضحة.","يجب على الآباء مراقبة استهلاك التلفاز.","ساعة واحدة يومياً مقبولة."],
    problem:{titleDe:"Spendensammlung für Straßenkinder",titleAr:"جمع المال لأطفال الشوارع",textDe:"Sie möchten Geld für Straßenkinder sammeln. Eine Wohltätigkeitsorganisation hat ein Programm.",textAr:"تريدون جمع المال لأطفال الشوارع. منظمة خيرية لديها برنامج."},
    problemIdeasDe:["Spendenaktion (Flohmarkt, Kuchenverkauf)","Spendenlauf in der Schule","Infostand in der Stadt","Kampagne in sozialen Medien","Wohltätigkeitskonzert","Briefe an Unternehmen schreiben"],
    problemIdeasAr:["حملة تبرعات (سوق خيري، بيع كعك)","جري رعائي في المدرسة","كشك معلومات في المدينة","حملة auf وسائل التواصل","حفلة خيرية","كتابة رسائل للشركات"]},
  {id:9,icon:"🎬",
    titleDe:"Fernsehen bildet",titleAr:"التلفاز يعلم",
    textDe:"Gute Wissenschaftssendungen können lehrreich sein. Voraussetzung: Selbstdisziplin und Programmwahl. Nur 8% der Kinder schauen auf Empfehlung ihrer Eltern.",
    textAr:"البرامج العلمية الجيدة يمكن أن تكون تعليمية. الشرط: الانضباط الذاتي واختيار البرامج. فقط 8% من الأطفال يشاهدون بتوصية من آبائهم.",
    proDe:["Dokumentationen vermitteln Wissen","Bilder wirken stärker als Texte","Ergänzung zum Schulunterricht","Fördern Interesse an Wissenschaft"],
    proAr:["الوثائقيات تنقل المعرفة","الصور تؤثر أقوى من النصوص","تكملة للتعليم المدرسي","تشجع الاهتمام بالعلوم"],
    contraDe:["Die meisten Sendungen sind Unterhaltung","Kinder brauchen Aufsicht","Wenige schauen bewusst","Kann Schule nicht ersetzen"],
    contraAr:["معظم البرامج ترفيهية","الأطفال يحتاجون إشرافاً","القليل يشاهدون بوعي","لا يمكن أن تحل محل المدرسة"],
    vocab:[{de:"die Bildungssendung",ar:"برنامج تعليمي"},{de:"die Dokumentation",ar:"الفيلم الوثائقي"},{de:"die Selbstdisziplin",ar:"الانضباط الذاتي"},{de:"die Programmwahl",ar:"اختيار البرامج"},{de:"die Ergänzung",ar:"التكملة"},{de:"die Unterhaltung",ar:"الترفيه"}],
    phrasesDe:["Wichtig ist die Auswahl der Sendungen.","Fernsehen kann bilden, wenn man bewusst wählt.","Eltern sollten mit Kindern übers Fernsehen sprechen."],
    phrasesAr:["المهم هو اختيار البرامج.","التلفاز يمكن أن يعلم إذا اخترت بوعي.","يجب على الآباء التحدث مع الأطفال عن المشاهدة."],
    problem:{titleDe:"Hilfe für ein Kind mit schlechten Noten",titleAr:"مساعدة طفل ذي درجات سيئة",textDe:"Ein 13-jähriges Kind hat schlechte Noten. Entwickeln Sie einen Plan, um zu helfen.",textAr:"طفل عمره 13 سنة درجاته سيئة. ضع خطة لمساعدته."},
    problemIdeasDe:["Mit dem Kind über die Gründe sprechen","Nachhilfe organisieren","Lernplan erstellen","Ruhigen Lernort schaffen","Mit Lehrern sprechen","Belohnungen für Verbesserungen"],
    problemIdeasAr:["التحدث مع الطفل عن الأسباب","تنظيم دروس خصوصية","إعداد خطة دراسة","توفير مكان هادئ للدراسة","التحدث مع المعلمين","مكافآت للتحسن"]},
  {id:10,icon:"🐶",
    titleDe:"Tiere als Geschenk",titleAr:"الحيوانات كهدية",
    textDe:"Tiere sind keine Ware, sondern Lebewesen mit langfristiger Verantwortung. Kinder verlieren schnell das Interesse. Ältere Menschen profitieren von Hunden (Bewegung, Gesellschaft).",
    textAr:"الحيوانات ليست بضاعة، بل كائنات حية بمسؤولية طويلة الأمد. الأطفال يفقدون الاهتمام بسرعة. كبار السن يستفيدون من الكلاب (حركة، رفقة).",
    proDe:["Große Freude für den Beschenkten","Verantwortung lernen für Kinder","Hund bringt Bewegung","Gesellschaft für Jahre"],
    proAr:["فرحة كبيرة للمهدى إليه","تعلم المسؤولية عند الأطفال","الكلب يجلب الحركة","رفقة لسنوات"],
    contraDe:["Langfristige Verantwortung","Kinder verlieren Interesse","Kosten für Futter und Tierarzt","Tier und Mensch müssen passen"],
    contraAr:["مسؤولية طويلة الأمد","الأطفال يفقدون الاهتمام","تكاليف الطعام والطبيب","الحيوان والإنسان يجب أن يتناسبا"],
    vocab:[{de:"das Haustier",ar:"الحيوان الأليف"},{de:"die Verantwortung",ar:"المسؤولية"},{de:"der tierische Begleiter",ar:"الرفيق الحيواني"},{de:"die Geschenkidee",ar:"فكرة هدية"},{de:"die Leichtfertigkeit",ar:"التهور"},{de:"der Vierbeiner",ar:"الكلب (صديق بأربع أرجل)"},{de:"der pädagogische Wert",ar:"القيمة التربوية"}],
    phrasesDe:["Ein Tier als Geschenk ist eine große Verantwortung.","Man sollte niemals spontan ein Tier verschenken.","Ältere Menschen profitieren sehr von einem Hund."],
    phrasesAr:["الحيوان كهدية مسؤولية كبيرة.","لا ينبغي أبداً إهداء حيوان بشكل عفوي.","كبار السن يستفيدون كثيراً من الكلب."],
    problem:{titleDe:"Schüleraustausch organisieren",titleAr:"تنظيم برنامج تبادل طلابي",textDe:"Ihre Schule nimmt an einem Austauschprogramm teil. Die Gastschüler bleiben 4 Wochen.",textAr:"مدرستك تشارك في برنامج تبادل. الطلاب الضيوف يبقون 4 أسابيع."},
    problemIdeasDe:["Unterbringung bei Gastfamilien","Sprachunterricht am Vormittag","Kulturelle Aktivitäten am Abend","Ausflüge in Nachbarstädte","Gemeinsames Kochen","Abschiedsparty"],
    problemIdeasAr:["إقامة عند عائلات مضيفة","دروس لغة في الصباح","أنشطة ثقافية في المساء","رحلات إلى المدن المجاورة","طبخ جماعي","حفلة وداع"]},
  {id:11,icon:"🚌",
    titleDe:"Sind Klassenfahrten sinnvoll?",titleAr:"هل الرحلات المدرسية مفيدة؟",
    textDe:"Klassenfahrten stärken den Klassenzusammenhalt. Schüler lernen sich besser kennen. Maximal 500 Euro, Ziele wie Berlin, Köln. Wünsche der Schüler sollten berücksichtigt werden.",
    textAr:"الرحلات المدرسية تقوي روح الفصل. يتعرف التلاميذ على بعضهم بشكل أفضل. حد أقصى 500 يورو، أهداف مثل برلين، كولونيا. يجب مراعاة رغبات التلاميذ.",
    proDe:["Stärkt den Klassenzusammenhalt","Bessere Beziehung zu Lehrern","Lernen außerhalb des Klassenzimmers","Kennenlernfahrt in der 5. Klasse"],
    proAr:["تقوي روح الفصل","علاقة أفضل مع المعلمين","تعلم خارج الفصل","رحلة تعارف في الصف الخامس"],
    contraDe:["Kann teuer sein","Lange Reisen (Australien) ungeeignet","Schlechte Organisation langweilt","Wenig Erholung"],
    contraAr:["قد تكون مكلفة","الرحلات الطويلة (أستراليا) غير مناسبة","التنظيم السيئ يسبب الملل","قليل من الاسترخاء"],
    vocab:[{de:"die Klassenfahrt",ar:"الرحلة المدرسية"},{de:"die Klassengemeinschaft",ar:"روح الفصل"},{de:"der Zusammenhalt",ar:"التماسك"},{de:"die Sehenswürdigkeit",ar:"المعلم السياحي"},{de:"die Stadtrallye",ar:"جولة في المدينة"},{de:"pädagogisch wertvoll",ar:"قيم تربوياً"}],
    phrasesDe:["Klassenfahrten sind wichtig für den Zusammenhalt.","Sie sollten nicht zu teuer sein, damit alle mitmachen können.","Die Wünsche der Schüler sollten berücksichtigt werden."],
    phrasesAr:["الرحلات المدرسية مهمة للتماسك.","يجب ألا تكون مكلفة حتى يتمكن الجميع من المشاركة.","يجب مراعاة رغبات التلاميذ."],
    problem:{titleDe:"Besuch im Kinderkrankenhaus",titleAr:"زيارة مستشفى الأطفال",textDe:"Organisieren Sie einen Besuch im Kinderkrankenhaus. Wie sieht das Programm aus?",textAr:"نظموا زيارة لمستشفى الأطفال. كيف يكون البرنامج؟"},
    problemIdeasDe:["Spiele und Aktivitäten vorbereiten","Bücher und Spielzeug mitbringen","Clowns oder Musiker einladen","Malen und Basteln","Mit dem Krankenhauspersonal abstimmen","Ruhezeiten beachten"],
    problemIdeasAr:["تحضير ألعاب وأنشطة","إحضار كتب وألعاب","دعوة مهرجين أو موسيقيين","الرسم والأشغال اليدوية","التنسيق مع طاقم المستشفى","مراعاة أوقات الراحة"]},
  {id:12,icon:"💸",
    titleDe:"Glücklich ohne Geld und Job",titleAr:"سعيد بدون مال ووظيفة",
    textDe:"Zwei Drittel der Praktikanten sind zufrieden trotz wenig Geld. Besonders in IT und Versicherungen. Je höher die Qualifikation, desto größer die Zufriedenheit.",
    textAr:"ثلثا المتدربين راضون رغم قلة المال. خاصة في تكنولوجيا المعلومات والتأمين. كلما كان المؤهل أعلى، كلما كان الرضا أكبر.",
    proDe:["Wertvolle Berufserfahrung","Einblick in die Arbeitswelt","Öffnet Türen für spätere Jobs","Besser als Arbeitslosigkeit"],
    proAr:["خبرة مهنية قيمة","نظرة إلى عالم العمل","يفتح أبواباً لفرص عمل لاحقة","أفضل من البطالة"],
    contraDe:["Niedrige Bezahlung","Keine Sicherheit (Generation Praktikum)","Ausbeuterische Bedingungen","Keine Übernahme nach dem Praktikum"],
    contraAr:["أجر ضعيف","لا أمان (جيل التدريب)","ظروف استغلالية","لا توظيف بعد التدريب"],
    vocab:[{de:"der Praktikant",ar:"المتدرب"},{de:"das Praktikum",ar:"التدريب"},{de:"die Berufserfahrung",ar:"الخبرة المهنية"},{de:"die Festanstellung",ar:"التوظيف الدائم"},{de:"die Branche",ar:"القطاع"},{de:"die Ausbeutung",ar:"الاستغلال"},{de:"die Zufriedenheit",ar:"الرضا"}],
    phrasesDe:["Ein Praktikum ist wichtig für die Berufserfahrung.","Praktikanten sollten fair bezahlt werden.","Nicht jeder kann sich ein unbezahltes Praktikum leisten."],
    phrasesAr:["التدريب مهم للخبرة المهنية.","يجب أن يحصل المتدربون على أجر عادل.","ليس الجميع يستطيع تحمل تدريب غير مدفوع."],
    problem:{titleDe:"Studienreise planen",titleAr:"تخطيط رحلة دراسية",textDe:"Eine Schülergruppe macht eine Studienreise in Ihr Heimatland.",textAr:"مجموعة تلاميذ تقوم برحلة دراسية إلى وطنك."},
    problemIdeasDe:["Land auswählen","Schulen und Universitäten besuchen","Bibliotheken und Forschungszentren","Vorträge organisieren","Kulturelle Aktivitäten","Sprachunterricht integrieren"],
    problemIdeasAr:["اختيار بلد","زيارة مدارس وجامعات","مكتبات ومراكز بحث","تنظيم محاضرات","أنشطة ثقافية","دمج دروس لغة"]},
  {id:13,icon:"☀️",
    titleDe:"Sonnenbank im Winter",titleAr:"الاستلقاء تحت الشمس in الشتاء",
    textDe:"Im Winter leiden viele unter Depressionen durch Lichtmangel. Sonnenbänke können helfen, aber Risiken: Hautkrebs, hohe Strahlung. Kinder und helle Haut: verboten.",
    textAr:"في الشتاء يعاني الكثيرون من الاكتئاب بسبب نقص الضوء. صالات الاستلقاء قد تساعد، لكن مخاطر: سرطان الجلد، إشعاع عالي. الأطفال والبشرة الفاتحة: ممنوع.",
    proDe:["Hilft gegen Winterdepression","Fördert Vitamin D","Verbessert die Stimmung","Schöne Bräune"],
    proAr:["يساعد ضد اكتئاب الشتاء","يشجع فيتامين د","يحسن المزاج","سمرة جميلة"],
    contraDe:["Erhöht Hautkrebsrisiko","Schädigt Hautzellen","Manche Geräte gefährlich","Besonders für Jugendliche"],
    contraAr:["يزيد خطر سرطان الجلد","يضر خلايا الجلد","بعض الأجهزة خطيرة","خاصة للمراهقين"],
    vocab:[{de:"das Solarium",ar:"صالة الاستلقاء تحت الشمس"},{de:"die Depression",ar:"الاكتئاب"},{de:"die Hautzellen",ar:"خلايا الجلد"},{de:"der Hautkrebs",ar:"سرطان الجلد"},{de:"die Strahlenbelastung",ar:"التعرض للإشعاع"},{de:"empfindliche Haut",ar:"البشرة الحساسة"},{de:"die Bräune",ar:"السمرة"}],
    phrasesDe:["Ein Solarium kann im Winter helfen, ist aber gefährlich.","Ich finde, frische Luft ist besser.","Vitamin D kann man auch über Nahrung aufnehmen."],
    phrasesAr:["صالة الاستلقاء قد تساعد in الشتاء لكنها خطيرة.","أرى أنه من الأفضل الخروج إلى الهواء الطلق.","فيتامين د يمكن الحصول عليه من الطعام أيضاً."],
    problem:{titleDe:"Informationstag zu Schule, Ausbildung und Beruf",titleAr:"تنظيم يوم معلومات عن المدرسة والتدريب والمهنة",textDe:"Organisieren Sie einen Informationstag zu Schule, Ausbildung und Beruf an Ihrer Schule.",textAr:"نظموا في مدرسة يوماً إعلامياً عن المدرسة والتدريب والمهنة."},
    problemIdeasDe:["Experten einladen","Vorträge über Berufsfelder","Ehemalige Schüler berichten","Infomaterial von Firmen und Unis","Technik und Räume organisieren","Verpflegung für Teilnehmer"],
    problemIdeasAr:["دعوة خبراء","محاضرات عن مجالات مهنية","خريجون سابقون يتحدثون","مواد إعلامية من شركات وجامعات","تنظيم التقنية والقاعات","تقديم وجبات للمشاركين"]},
  {id:14,icon:"😂",
    titleDe:"Gesund durch Lachen",titleAr:"الصحة بالضحك",
    textDe:"Kinder lachen bis zu 400 Mal am Tag, Erwachsene nur 15 Mal. Lachen stärkt das Immunsystem, lindert Schmerz. In Krankenhäusern werden Clowns in der Therapie eingesetzt.",
    textAr:"الأطفال يضحكون حتى 400 مرة في اليوم، البالغون فقط 15 مرة. الضحك يقوي المناعة، يخفف الألم. في المستشفيات يستخدمون المهرجين في العلاج.",
    proDe:["Stärkt das Immunsystem","Reduziert Stress und Schmerz","Verbessert die Stimmung","Stärkt soziale Bindungen"],
    proAr:["يقوي جهاز المناعة","يخفف التوتر والألم","يحسن المزاج","يقوي الروابط الاجتماعية"],
    contraDe:["Lachen kann ausgrenzen","Nicht in allen Kulturen gleich","Hämisches Lachen verletzt","Erwachsene lachen wenig"],
    contraAr:["الضحك قد يستثني","ليس نفسه في كل الثقافات","الضحك الخبيث يؤذي","البالغون يضحكون قليلاً"],
    vocab:[{de:"das Lachen",ar:"الضحك"},{de:"die Lachforschung",ar:"أبحاث الضحك"},{de:"das Immunsystem",ar:"جهاز المناعة"},{de:"die Entspannung",ar:"الاسترخاء"},{de:"der Clown",ar:"المهرج"},{de:"die Therapie",ar:"العلاج"},{de:"der Stress",ar:"التوتر"}],
    phrasesDe:["Lachen ist gesund – das ist wissenschaftlich bewiesen.","Erwachsene sollten mehr lachen wie Kinder.","Humor ist wichtig für die Gesundheit."],
    phrasesAr:["الضحك صحي – وهذا مثبت علمياً.","يجب على البالغين أن يضحكوا أكثر مثل الأطفال.","الفكاهة مهمة للصحة."],
    problem:{titleDe:"Straßenfest organisieren",titleAr:"تنظيم مهرجان شارع",textDe:"Sie möchten ein Straßenfest in Ihrer Nachbarschaft mit allen Nachbarn organisieren.",textAr:"تريد تنظيم مهرجان in شارعك مع جميع الجيران."},
    problemIdeasDe:["Datum und Uhrzeit festlegen","Essen und Trinken (jeder bringt etwas mit)","Musik und Spiele für Kinder","Tische und Stühle auf der Straße","Einladungen verteilen","Budget und Aufgaben verteilen"],
    problemIdeasAr:["تحديد التاريخ والوقت","الطعام والشراب (الجميع يحضر شيئاً)","موسيقى وألعاب للأطفال","وضع طاولات وكراسي in الشارع","توزيع الدعوات","توزيع الميزانية والمهام"]},
  {id:15,icon:"🍺",
    titleDe:"Selber kochen schmeckt besser",titleAr:"الطبخ بنفسك أطيب",
    textDe:"84% der Deutschen sagen: Selber kochen schmeckt besser. Man weiß, was drin ist, frische Zutaten. Fertiggerichte sind bequem, aber weniger gesund.",
    textAr:"84% من الألمان يقولون: الطبخ بنفسك أطيب. تعرف ما in الطعام، مكونات طازجة. الوجبات الجاهزة مريحة لكنها أقل صحة.",
    proDe:["Man weiß, was drin ist","Frische und Qualität","Keine Konservierungsstoffe","Nach Bedarf anpassbar"],
    proAr:["تعرف ما in الطعام","نضارة وجودة","لا مواد حافظة","قابل للتعديل حسب الاحتياج"],
    contraDe:["Braucht Zeit und Planung","Erfordert Kochkenntnisse","Nach der Arbeit anstrengend","Teurer als Fertiggerichte?"],
    contraAr:["يحتاج وقتاً وتخطيطاً","يتطلب مهارات طبخ","بعد العمل متعب","أغلى من الوجبات الجاهزة؟"],
    vocab:[{de:"die Zutat",ar:"المكون"},{de:"der Konservierungsstoff",ar:"المادة الحافظة"},{de:"der Geschmack",ar:"الطعم"},{de:"das Fertiggericht",ar:"الوجبة الجاهزة"},{de:"der Wochenmarkt",ar:"سوق الأسبوع"},{de:"die Allergie",ar:"الحساسية"},{de:"das Selberkochen",ar:"الطبخ المنزلي"}],
    phrasesDe:["Selber kochen ist gesünder als Fertiggerichte.","Fertiggerichte sind praktisch, aber ungesund.","Frische Zutaten schmecken einfach besser."],
    phrasesAr:["الطبخ المنزلي أصح من الوجبات الجاهزة.","الوجبات الجاهزة عملية لكنها غير صحية.","المكونات الطازجة أطعم ببساطة."],
    problem:{titleDe:"Sportevent für Kinder",titleAr:"تنظيم حدث رياضي للأطفال",textDe:"Organisieren Sie ein Sportereignis für Kinder in Ihrer Stadt.",textAr:"نظم حدثاً رياضياً للأطفال in مدينتك."},
    problemIdeasDe:["Verschiedene Sportarten anbieten","Wettkämpfe nach Alter","Urkunden und Medaillen","Erste-Hilfe-Station","Verpflegung organisieren","Eltern als Helfer einbeziehen"],
    problemIdeasAr:["تقديم رياضات مختلفة","مسابقات حسب العمر","شهادات وميداليات","محطة إسعافات أولية","تنظيم الطعام","إشراك الآباء كمساعدين"]},
  {id:16,icon:"📅",
    titleDe:"Arbeiten bis 75?",titleAr:"العمل حتى 75 سنة؟",
    textDe:"Die Lebenserwartung steigt (70->81). Das Rentensystem ist nicht finanzierbar. Lösung: Renteneintrittsalter erhöhen oder flexibel gestalten. Aber Ältere haben Schwierigkeiten, Arbeit zu finden.",
    textAr:"متوسط العمر يزداد (70->81). نظام التقاعد غير قابل للتمويل. حل: رفع سن التقاعد أو جعله مرناً. لكن كبار السن يجدون صعوبة in العثور على عمل.",
    proDe:["Rentensystem sonst nicht finanzierbar","Menschen bleiben länger gesund","Wissenstransfer an Junge","Flexible Rente ist optimal"],
    proAr:["نظام التقاعد غير قابل للتمويل وإلا","الناس يبقون أصحاء لفترة أطول","نقل المعرفة للشباب","تقاعد مرن هو الأمثل"],
    contraDe:["Ältere schwer vermittelbar","Nicht alle können körperlich arbeiten","Krankheiten nehmen nach 65 zu","Junge brauchen Chancen"],
    contraAr:["كبار السن يجدون صعوبة in التوظيف","لا يستطيع الجميع العمل جسدياً","الأمراض تزيد بعد 65","الشباب يحتاجون فرص العمل"],
    vocab:[{de:"die Rente",ar:"التقاعد / المعاش"},{de:"das Rentensystem",ar:"نظام التقاعد"},{de:"das Renteneintrittsalter",ar:"سن التقاعد"},{de:"die Lebenserwartung",ar:"متوسط العمر المتوقع"},{de:"der Arbeitnehmer",ar:"الموظف"},{de:"die Flexibilisierung",ar:"المرونة"},{de:"der Pensionsschock",ar:"صدمة المعاش"}],
    phrasesDe:["Arbeiten bis 75 ist für viele unrealistisch.","Das Rentensystem braucht eine Reform.","Ich bin für eine flexible Rente."],
    phrasesAr:["العمل حتى 75 غير واقعي لكثير من الناس.","نظام التقاعد يحتاج إصلاحاً.","أنا مع تقاعد مرن."],
    problem:{titleDe:"Beim Umzug helfen",titleAr:"مساعدة in الانتقال",textDe:"Ihr Freund möchte in eine andere Stadt ziehen. Wie können Sie helfen?",textAr:"صديقك يريد الانتقال إلى مدينة أخرى. كيف يمكنك مساعدته؟"},
    problemIdeasDe:["Beim Packen helfen","Umzugswagen organisieren","Möbel tragen","Neue Wohnung putzen","Bei Adressänderung helfen","Einweihungsparty planen"],
    problemIdeasAr:["المساعدة in تعبئة الكراتين","تنظيم سيارة نقل","حمل الأثاث","تنظيف الشقة الجديدة","مساعدة in تغيير العنوان","تخطيط حفلة تدشين"]},
  {id:17,icon:"🏆",
    titleDe:"Schuluniform – Pro und Contra",titleAr:"الزي المدرسي – مؤيد ومعارض",
    textDe:"Schuluniform kann Gruppenzwang reduzieren. Stärkt das Gemeinschaftsgefühl. Kritik: schränkt Persönlichkeit ein, löst keine tieferen Probleme.",
    textAr:"الزي المدرسي يمكن أن يقلل ضغط الأقران. يقوي روح الجماعة. النقد: يحد من الشخصية، لا يحل المشاكل العميقة.",
    proDe:["Reduziert Markenzwang","Stärkt Gemeinschaftsgefühl","Verhindert Ausgrenzung","Mehr Fokus auf den Inhalt"],
    proAr:["يقلل ضغط الماركات","يقوي روح الجماعة","يمنع الاستبعاد","تركيز أكثر على المحتوى"],
    contraDe:["Schränkt Persönlichkeit ein","Löst keine tieferen Probleme","Kann teuer sein","Zwang statt Freiheit"],
    contraAr:["يحد من الشخصية","لا يحل المشاكل العميقة","قد يكون مكلفاً","إجبار بدلاً من حرية"],
    vocab:[{de:"die Schuluniform",ar:"الزي المدرسي"},{de:"der Gruppenzwang",ar:"ضغط الأقران"},{de:"die Ausgrenzung",ar:"الاستبعاد"},{de:"das Zusammengehörigkeitsgefühl",ar:"روح الانتماء"},{de:"die Integration",ar:"الاندماج"},{de:"die Persönlichkeit",ar:"الشخصية"},{de:"der Dialog",ar:"الحوار"}],
    phrasesDe:["Schuluniform kann den Markenzwang reduzieren.","Aber sie schränkt die Persönlichkeitsentfaltung ein.","Am wichtigsten ist Toleranz zu lehren."],
    phrasesAr:["الزي المدرسي يمكن أن يقلل ضغط الماركات.","لكنه يحد من حرية التعبير عن الشخصية.","الأهم هو تعليم التسامح."],
    problem:{titleDe:"Freundin beim Umzug helfen",titleAr:"مساعدة صديقة in الانتقال",textDe:"Ihre Freundin möchte umziehen. Wie helfen Sie?",textAr:"صديقتك تريد الانتقال. كيف تساعد؟"},
    problemIdeasDe:["Kartons besorgen und beim Packen helfen","Umzugsfirma suchen","Beim Tragen helfen","Kinder betreuen","Essen für den Umzugstag organisieren","Pflanzen oder Deko mitbringen"],
    problemIdeasAr:["توفير كراتين والمساعدة in التعبئة","البحث عن شركة نقل","المساعدة in الحمل","رعاية الأطفال","تنظيم الطعام ليوم النقل","إحضار نباتات أو ديكور"]},
  {id:18,icon:"🏽",
    titleDe:"Leistungssport und Doping",titleAr:"الرياضة التنافسية والمنشطات",
    textDe:"Doping im Sport ist ein Problem. Manche fordern Freigabe, weil die Gesellschaft auch Dopingmittel verwendet. Gegner: unfair, ungesund, zerstört Vorbildfunktion des Sports.",
    textAr:"المنشطات in الرياضة مشكلة. البعض يطالب بالترخيص لأن المجتمع يستخدم المنشطات أيضاً. المعارضون: غير عادل، غير صحي، يدمر قدوة الرياضة.",
    proDe:["Kontrollen leicht umgehbar","Gesellschaft nutzt auch Dopingmittel","Freigabe schafft Ehrlichkeit"],
    proAr:["الفحوصات سهلة التجاوز","المجتمع يستخدم المنشطات أيضاً","الترخيص يخلق الصدق"],
    contraDe:["Ungesund und gefährlich","Unfair für saubere Sportler","Zerstört Vorbildfunktion","Ermutigt Hobbysportler"],
    contraAr:["غير صحي وخطير","غير عادل للرياضيين النظيفين","يدمر وظيفة القدوة","يشجع الرياضيين الهواة"],
    vocab:[{de:"das Doping",ar:"المنشطات"},{de:"der Leistungssport",ar:"الرياضة التنافسية"},{de:"die Dopingkontrolle",ar:"فحص المنشطات"},{de:"die Freigabe",ar:"الترخيص"},{de:"die Chancengleichheit",ar:"تكافؤ الفرص"},{de:"die Vorbildfunktion",ar:"وظيفة القدوة"},{de:"der Missbrauch",ar:"إساءة الاستخدام"}],
    phrasesDe:["Doping ist unfair und gefährlich.","Sport sollte eine Vorbildfunktion haben.","Die Kontrollen müssen verbessert werden."],
    phrasesAr:["المنشطات غير عادلة وخطيرة.","الرياضة يجب أن تكون قدوة.","يجب تحسين الفحوصات."],
    problem:{titleDe:"Software-Seminar organisieren",titleAr:"تنظيم ندوة برمجيات",textDe:"Organisieren Sie ein Seminar über Software. Entwickeln Sie Vorschläge.",textAr:"نظم ندوة عن البرمجيات. طوروا اقتراحات."},
    problemIdeasDe:["Thema festlegen","Zielgruppe bestimmen","Referenten suchen","Raum mit Computern buchen","Programm erstellen","Teilnahmezertifikate"],
    problemIdeasAr:["تحديد الموضوع","تحديد الفئة المستهدفة","البحث عن محاضرين","حجز قاعة بأجهزة كمبيوتر","إعداد برنامج الندوة","شهادات للمشاركين"]},
  {id:19,icon:"🎉",
    titleDe:"Wie lange dürfen Jugendliche abends raus?",titleAr:"كم من الوقت مسموح للمراهقين بالخروج ليلاً؟",
    textDe:"Das Jugendschutzgesetz regelt den Aufenthalt Jugendlicher an bestimmten Orten. Eltern entscheiden. Wichtig: Vertrauen zwischen Eltern und Kindern.",
    textAr:"قانون حماية الشباب ينظم تواجد المراهقين in أماكن معينة. الآباء يقررون. المهم: الثقة بين الآباء والأبناء.",
    proDe:["Jugendliche brauchen Freiheit","Vertrauen stärkt die Beziehung","Feste Regeln geben Orientierung","Fördert Selbstständigkeit"],
    proAr:["المراهقون بحاجة للحرية","الثقة تقوي العلاقة","قواعد ثابتة تعطي التوجيه","تشجع الاستقلالية"],
    contraDe:["Eltern wollen schützen","Risiken werden unterschätzt","Schlechte Einflüsse nachts","Schlafmangel schadet der Schule"],
    contraAr:["الآباء يريدون الحماية","المخاطر قد لا يقدرونها","تأثيرات سيئة ليلاً","قلة النوم تضر المدرسة"],
    vocab:[{de:"der Ausgang",ar:"الخروج"},{de:"das Jugendschutzgesetz",ar:"قانون حماية الشباب"},{de:"die Aufsichtspflicht",ar:"واجب الإشراف"},{de:"die Eigenverantwortung",ar:"المسؤولية الشخصية"},{de:"das Vertrauen",ar:"الثقة"},{de:"die Selbstständigkeit",ar:"الاستقلالية"},{de:"der Kompromiss",ar:"الحل الوسط"}],
    phrasesDe:["Jugendliche brauchen Grenzen, aber auch Vertrauen.","Man sollte die Ausgehzeiten gemeinsam vereinbaren.","Ein Kompromiss zwischen Freiheit und Schutz ist wichtig."],
    phrasesAr:["المراهقون بحاجة لحدود لكن أيضاً ثقة.","يجب الاتفاق على أوقات الخروج معاً.","الحل الوسط بين الحرية والحماية مهم."],
    problem:{titleDe:"Blutspendeaktion organisieren",titleAr:"تنظيم حدث للتبرع بالدم",textDe:"Organisieren Sie eine Blutspendeaktion in einem Gesundheitszentrum.",textAr:"نظموا حدثاً للتبرع بالدم in مركز صحي."},
    problemIdeasDe:["Datum und Ort festlegen","Werbung und Plakate","Informationsmaterial zur Spende","Mobiles Spende-Team","Helfer einteilen","Getränke für Spender"],
    problemIdeasAr:["تحديد التاريخ والمكان","إعلان وملصقات","مواد إعلامية عن التبرع","وحدة متنقلة للتبرع","توزيع المساعدين","مشروبات للمتبرعين"]},
  {id:20,icon:"💉",
    titleDe:"Antibiotika – Alternativen",titleAr:"المضادات الحيوية – بدائل",
    textDe:"Antibiotikaresistenzen nehmen zu durch übermäßige Verschreibung und falsche Anwendung. Alternativen: Heilpflanzen (Salbei, Thymian). Aber bei schweren Infektionen unverzichtbar.",
    textAr:"مقاومة المضادات الحيوية تزداد بسبب الإفراط in الوصف والاستخدام الخاطئ. بدائل: نباتات طبية (مريمية، زعتر). لكن in الالتهابات الخطيرة لا غنى عنها.",
    proDe:["Retten Leben bei Infektionen","Moderne Medizin","Gut erforscht","Schnelle Wirkung"],
    proAr:["تنقذ الأرواح in الالتهابات","دواء حديث","مدروس جيداً","تأثير سريع"],
    contraDe:["Resistenzen nehmen zu","Werden oft unnötig verschrieben","Mögliche Nebenwirkungen","Falsche Anwendung durch Patienten"],
    contraAr:["المقاومة تزداد","توصف بدون داعي غالباً","آثار جانبية محتملة","استخدام خاطئ من المرضى"],
    vocab:[{de:"das Antibiotikum",ar:"المضاد الحيوي"},{de:"die Resistenz",ar:"المقاومة"},{de:"das Bakterium",ar:"البكتيريا"},{de:"die Entzündung",ar:"الالتهاب"},{de:"die Heilpflanze",ar:"النبات الطبي"},{de:"die Nebenwirkung",ar:"الآثار الجانبية"},{de:"die Behandlung",ar:"العلاج"}],
    phrasesDe:["Antibiotika sind wichtig, aber nicht für jede Krankheit.","Resistenzen sind ein großes Problem.","Heilpflanzen können bei leichten Entzündungen helfen."],
    phrasesAr:["المضادات الحيوية مهمة لكن ليس لكل مرض.","المقاومة مشكلة كبيرة.","النباتات الطبية قد تساعد in الالتهابات الخفيفة."],
    problem:{titleDe:"Informationstag zu neuen Medien",titleAr:"يوم معلومات عن الوسائط الجديدة",textDe:"Informationstag über Internet und Smartphones.",textAr:"يوم معلومات عن الإنترنت والهواتف الذكية."},
    problemIdeasDe:["Vorträge über Internetsicherheit","Nutzung von Smartphones","Prävention von Cybermobbing","Workshop Datenschutz","Infomaterial gestalten","Experten einladen"],
    problemIdeasAr:["محاضرات عن الأمان على الإنترنت","استخدام الهواتف الذكية","الوقاية من التنمر الإلكتروني","ورشة حماية البيانات","تصميم مواد إعلامية","دعوة خبراء"]},
  {id:21,icon:"🏡",
    titleDe:"Haustausch",titleAr:"تبادل المنازل",
    textDe:"Günstige Ferien durch Haustausch. Andere Kultur erleben, keine Hotels. Nachteile: rechtliche Risiken, unklare Haftung, braucht Vertrauen.",
    textAr:"عطلات رخيصة بتبادل المنازل. تجربة ثقافة أخرى، لا فنادق. عيوب: مخاطر قانونية، مسؤولية غير واضحة، تحتاج ثقة.",
    proDe:["Sehr günstig","Andere Kultur erleben","Keine Hotelkosten","Flexibel"],
    proAr:["رخيص جداً","تجربة ثقافة أخرى","لا تكاليف فنادق","مرن"],
    contraDe:["Rechtliche Risiken","Haftung für Schäden unklar","Reinheitsstandards unbekannt","Braucht viel Vertrauen"],
    contraAr:["مخاطر قانونية","المسؤولية عن الأضرار غير واضحة","معايير النظافة غير معروفة","يحتاج ثقة كبيرة"],
    vocab:[{de:"der Haustausch",ar:"تبادل المنازل"},{de:"der Tauschpartner",ar:"شريك التبادل"},{de:"die Haftungsfrage",ar:"مسألة المسؤولية"},{de:"der Vertrag",ar:"العقد"},{de:"der Schaden",ar:"الضرر"},{de:"der Vermittler",ar:"الوسيط"},{de:"das Vertrauen",ar:"الثقة"}],
    phrasesDe:["Haustausch ist eine tolle Möglichkeit für günstiges Reisen.","Rechtlich ist das nicht immer abgesichert.","Vertrauen ist die wichtigste Voraussetzung."],
    phrasesAr:["تبادل المنازل فرصة رائعة للسفر الرخيص.","قانونياً هذا غير مضمون دائماً.","الثقة هي أهم شرط."],
    problem:{titleDe:"Hilfe bei einem Vortrag über Deutsch lernen",titleAr:"مساعدة in محاضرة لتعليم الألمانية",textDe:"Ihre Lehrerin hat Sie zu einem Vortrag über Deutsch als Fremdsprache eingeladen.",textAr:"معلمتك دعتك لمحاضرة عن الألمانية كلغة أجنبية."},
    problemIdeasDe:["Bei der Materialvorbereitung helfen","Vortrag über Ihr Land halten","Mit Muttersprache unterstützen","Übungen für Anfänger vorbereiten","Kulturelle Unterschiede erklären","Kaffeepause organisieren"],
    problemIdeasAr:["المساعدة in تحضير المواد","تقديم عرض عن بلدك","دعم باللغة الأم","تحضير تمارين للمبتدئين","شرح الفروق الثقافية","تنظيم استراحة القهوة"]},
  {id:22,icon:"🎤",
    titleDe:"Zweisprachigkeit bei Kindern",titleAr:"ثنائية اللغة عند الأطفال",
    textDe:"Die meisten Menschen sind zweisprachig. Vorteile: bessere kognitive Fähigkeiten, kulturelle Identität, Berufschancen. Kinder lernen intuitiv. Früher dachte man, es verwirrt Kinder.",
    textAr:"معظم الناس ثنائيو اللغة. مزايا: قدرات معرفية أفضل، هوية ثقافية، فرص مهنية. الأطفال يتعلمون بشكل حدسي. سابقاً كان يعتقد أنه يربك الأطفال.",
    proDe:["Kognitive Vorteile","Kulturelle Identität","Berufschancen","Intuitives Lernen"],
    proAr:["مزايا معرفية","هوية ثقافية","فرص مهنية","تعلم حدسي"],
    contraDe:["Mögliche Sprachverwirrung","Braucht Beharrlichkeit der Eltern","Eltern müssen beide Sprachen können","Möglicher Akzent"],
    contraAr:["ارتباك لغوي محتمل","يحتاج إصراراً من الآباء","الآباء يجب أن يتقنوا اللغتين","احتمال لكنة"],
    vocab:[{de:"die Zweisprachigkeit",ar:"ثنائية اللغة"},{de:"die kognitive Fähigkeit",ar:"القدرة المعرفية"},{de:"die kulturelle Identität",ar:"الهوية الثقافية"},{de:"intuitiv",ar:"حدسي"},{de:"die Sprachverwirrung",ar:"الارتباك اللغوي"},{de:"der Akzent",ar:"اللكنة"},{de:"der Spracherwerb",ar:"اكتساب اللغة"}],
    phrasesDe:["Zweisprachigkeit ist ein großer Vorteil.","Kinder lernen Sprachen leichter als Erwachsene.","Ich würde meine Kinder zweisprachig erziehen."],
    phrasesAr:["ثنائية اللغة ميزة كبيرة.","الأطفال يتعلمون اللغات أسهل من الكبار.","سأربي أطفالي ثنائيي اللغة."],
    problem:{titleDe:"Spielemesse organisieren",titleAr:"تنظيم معرض ألعاب",textDe:"In einem Kulturzentrum findet eine Spielemesse statt.",textAr:"in مركز ثقافي سيقام معرض ألعاب."},
    problemIdeasDe:["Datum und Ort festlegen","Verschiedene Spielbereiche","Spiele zum Ausprobieren","Turniere organisieren","Werbung und Plakate","Café oder Imbiss"],
    problemIdeasAr:["تحديد التاريخ والمكان","أقسام ألعاب مختلفة","ألعاب للتجربة","تنظيم بطولات","مواد إعلامية وملصقات","مقهى أو مطعم"]},
  {id:23,icon:"💑",
    titleDe:"Heiraten ohne Gäste",titleAr:"الزواج بدون ضيوف",
    textDe:"Immer mehr Paare heiraten ohne Gäste. Gründe: Kosten sparen, Stress vermeiden. 38% max. 5.000 Euro, 9% nur 1.000 Euro.",
    textAr:"المزيد من الأزواج يتزوجون بدون ضيوف. الأسباب: توفير التكاليف، تجنب التوتر. 38% حد أقصى 5.000 يورو، 9% فقط 1.000 يورو.",
    proDe:["Weniger Stress und Kosten","Intimer und persönlicher","Keine Verpflichtungen","Mehr Freiheit"],
    proAr:["توتر وتكاليف أقل","حميمي وشخصي أكثر","لا التزامات","حرية أكثر"],
    contraDe:["Familie könnte enttäuscht sein","Feiern macht Spaß","Tradition geht verloren","Weniger Erinnerungen mit anderen"],
    contraAr:["العائلة قد تشعر بخيبة أمل","الاحتفال ممتع","التقليد يضيع","ذكريات أقل مع الآخرين"],
    vocab:[{de:"die Hochzeit",ar:"الزواج"},{de:"der Standesbeamte",ar:"موظف الأحوال المدنية"},{de:"die Trauung",ar:"مراسم الزواج"},{de:"die Feierlichkeiten",ar:"الاحتفالات"},{de:"die Flitterwochen",ar:"شهر العسل"},{de:"die Zeremonie",ar:"الحفل"},{de:"der finanzielle Aufwand",ar:"المصاريف المالية"}],
    phrasesDe:["Jeder hat das Recht, so zu heiraten, wie er möchte.","Eine kleine Hochzeit ist intimer.","Das ist eine sehr persönliche Entscheidung."],
    phrasesAr:["لكل شخص الحق in الزواج كما يريد.","الزواج الصغير أكثر حميمية.","إنه قرار شخصي جداً."],
    problem:{titleDe:"Reise in ein deutschsprachiges Land planen",titleAr:"تخطيط رحلة إلى بلد ناطق بالألمانية",textDe:"Die Kursteilnehmer möchten eine Reise nach Deutschland/Österreich/Schweiz machen.",textAr:"المشاركون in الدورة يريدون رحلة إلى ألمانيا / النمسا / سويسرا."},
    problemIdeasDe:["Ziel auswählen","Reisedauer festlegen","Unterkunft buchen","Besichtigungen planen","Sprachpraxis integrieren","Budget berechnen"],
    problemIdeasAr:["اختيار الوجهة","تحديد مدة الرحلة","حجز الإقامة","تخطيط الزيارات","دمج ممارسة اللغة","حساب الميزانية"]},
  {id:24,icon:"👨‍⚕️",
    titleDe:"Schönheitsoperationen bei Minderjährigen",titleAr:"عمليات التجميل للقاصرين",
    textDe:"Politiker fordern ein Verbot unnötiger Schönheitsoperationen bei Minderjährigen. Ausnahme: medizinisch notwendig. Gegner: Grenzen schwer zu ziehen. Aufklärung wichtiger als Verbot.",
    textAr:"سياسيون يطالبون بحظر عمليات التجميل غير الضرورية للقاصرين. استثناء: الضروريات طبية. المعارضون: الحدود صعبة التحديد. التوعية أهم من الحظر.",
    proDe:["Schutz von Minderjährigen","Körperakzeptanz fördern","Körper ist in Entwicklung","Verhindert Körperverletzung"],
    proAr:["حماية القاصرين","حب الجسد كما هو","الجسم in تطور","يمنع الإيذاء الجسدي"],
    contraDe:["Grenzen schwer zu ziehen","Elternrechte eingeschränkt","Verbot löst keine falschen Ideale","Ärzte sollten entscheiden"],
    contraAr:["الحدود صعبة التحديد","حقوق الآباء مقيدة","الحظر لا يحل المثل الخاطئة","الأطباء يجب أن يقرروا"],
    vocab:[{de:"die Schönheitsoperation",ar:"عملية التجميل"},{de:"der Minderjährige",ar:"القاصر"},{de:"das Verbot",ar:"الحظر"},{de:"die Körperverletzung",ar:"الإيذاء الجسدي"},{de:"das Schönheitsideal",ar:"المثالية الجمالية"},{de:"der Eingriff",ar:"التدخل الجراحي"},{de:"das Selbstbewusstsein",ar:"الثقة بالنفس"}],
    phrasesDe:["Schönheitsoperationen bei Minderjährigen sind problematisch.","Aufklärung über falsche Ideale ist wichtig.","Jugendliche sollten lernen, sich selbst zu akzeptieren."],
    phrasesAr:["عمليات التجميل للقاصرين مشكلة.","التوعية عن المثل الخاطئة مهمة.","المراهقون يجب أن يتعلموا قبول أنفسهم."],
    problem:{titleDe:"Einsame Nachbarin im Krankenhaus",titleAr:"جارة وحيدة in المستشفى",textDe:"Ihre einsame Nachbarin ist ins Krankenhaus gekommen. Helfen Sie, ihre Kinder zu versorgen.",textAr:"جارتك الوحيدة دخلت المستشفى. ساعد in رعاية أطفالها."},
    problemIdeasDe:["Kinder von der Schule abholen","Essen kochen","Bei Hausaufgaben helfen","Übernachtung organisieren","Mit Kindern spielen","Einkäufe erledigen"],
    problemIdeasAr:["اصطحاب الأطفال من المدرسة","طهي الطعام","المساعدة in الواجبات","تنظيم المبيت","اللعب مع الأطفال","شراء الحاجيات"]},
  {id:25,icon:"🏫",
    titleDe:"Ganztagsschulen",titleAr:"المدارس اليوم الكامل",
    textDe:"Trend zu Ganztagsschulen. 2002: 10%, 2016: 42,5%. 78% befürworten Ausbau. Definition: mindestens 7 Stunden an 3 Tagen.",
    textAr:"اتجاه نحو مدارس اليوم الكامل. 2002: 10%، 2016: 42.5%. 78% يؤيدون التوسع. تعريف: 7 ساعات على الأقل in 3 أيام.",
    proDe:["Bessere Betreuung","Mehr Zeit für Bildung","Entlastung berufstätiger Eltern","Nachmittagsangebote"],
    proAr:["رعاية أفضل","وقت أكثر للتعليم","تخفيف عن الآباء العاملين","عروض ما بعد الظهر"],
    contraDe:["Weniger Familienzeit","Lange Tage ermüden","Kein einheitliches Konzept","Kosten für Bundesländer"],
    contraAr:["وقت أقل للعائلة","الأيام الطويلة تتعب","لا مفهوم موحد","تكاليف على الولايات"],
    vocab:[{de:"die Ganztagsschule",ar:"مدرسة اليوم الكامل"},{de:"die Betreuung",ar:"الرعاية"},{de:"die Chancengleichheit",ar:"تكافؤ الفرص"},{de:"die Schulform",ar:"نوع المدرسة"},{de:"der Ausbau",ar:"التوسع"},{de:"die Ganztagsbetreuung",ar:"رعاية اليوم الكامل"}],
    phrasesDe:["Ganztagsschulen entlasten berufstätige Eltern.","Kinder brauchen aber auch Familienzeit.","Das Konzept ist wichtiger als die Dauer."],
    phrasesAr:["مدارس اليوم الكامل تخفف عن الآباء العاملين.","الأطفال يحتاجون أيضاً وقتاً عائلياً.","المفهوم الجيد أهم من المدة."],
    problem:{titleDe:"Freund aus Amerika in den Ferien helfen",titleAr:"مساعدة صديق من أمريكا in العطلة",textDe:"Ein Freund aus Amerika kommt nach Deutschland.",textAr:"صديق من أمريكا يأتي إلى ألمانيا."},
    problemIdeasDe:["Sehenswürdigkeiten zeigen","Restaurants empfehlen","Öffentliche Verkehrsmittel erklären","Gemeinsame Aktivitäten","Kulturelle Tipps geben","Party mit Freunden"],
    problemIdeasAr:["إظهار المعالم السياحية","توصية بمطاعم","شرح وسائل النقل العامة","أنشطة مشتركة","نصائح ثقافية","حفلة مع الأصدقاء"]},
  {id:26,icon:"🎮",
    titleDe:"Verbot von Gewaltspielen",titleAr:"حظر ألعاب العنف",
    textDe:"Nach Amokläufen wird ein Verbot von Gewaltspielen gefordert. Experten: Gewalt ist komplex. Eltern und Lehrer sind wichtiger als Verbote.",
    textAr:"بعد حوادث إطلاق النار يُطالب بحظر ألعاب العنف. الخبراء: العنف معقد. الآباء والمعلمون أهم من الحظر.",
    proDe:["Schutz vor schädlichen Inhalten","Gewalt als Lösung wird gelernt","Prävention von Angriffen"],
    proAr:["حماية من المحتوى الضار","العنف كحل يُتعلم","الوقاية من الهجمات"],
    contraDe:["Verbot schwer durchsetzbar","Ursachen komplexer","Lenkt von echten Problemen ab","Eltern und Umfeld wichtiger"],
    contraAr:["الحظر صعب التنفيذ","الأسباب أكثر تعقيداً","يصرف عن المشاكل الحقيقية","الآباء والبيئة أهم"],
    vocab:[{de:"das Gewaltspiel",ar:"لعبة عنف"},{de:"der Amoklauf",ar:"هجوم إطلاق نار"},{de:"das Verbot",ar:"الحظر"},{de:"die Gewalt",ar:"العنف"},{de:"die Prävention",ar:"الوقاية"},{de:"die Verherrlichung",ar:"التمجيد"},{de:"das Umfeld",ar:"البيئة المحيطة"}],
    phrasesDe:["Ein Verbot allein reicht nicht.","Eltern und Lehrer sind die wichtigsten Vorbilder.","Medienkompetenz ist wichtiger als Verbote."],
    phrasesAr:["الحظر وحده لا يكفي.","الآباء والمعلمون أهم قدوة.","الثقافة الإعلامية أهم من الحظر."],
    problem:{titleDe:"Museumsbesuch planen",titleAr:"تخطيط زيارة متحف",textDe:"Museumsbesuch mit Sprachkurs-Teilnehmern.",textAr:"زيارة متحف مع زملاء دورة اللغة."},
    problemIdeasDe:["Museum auswählen","Führung buchen","Eintrittspreise prüfen","Anreise gemeinsam organisieren","Nachbesprechung","Audioguide auf Deutsch nutzen"],
    problemIdeasAr:["اختيار المتحف","حجز جولة إرشادية","التحقق من أسعار الدخول","تنظيم الوصول معاً","مناقشة بعد الزيارة","استخدام دليل صوتي بالألمانية"]},
  {id:27,icon:"📚",
    titleDe:"Lerntipps für die Praxis",titleAr:"نصائح تعلم عملية",
    textDe:"Multikanallernen: Hören 20%, Sehen 30%, +Sprechen 70%, +Tun 90%. Tipps: Zusammenfassen, Diagramme, Wiederholung, Lernplan, Pausen.",
    textAr:"التعلم متعدد القنوات: سماع 20%، رؤية 30%، +كلام 70%، +فعل 90%. نصائح: تلخيص، رسوم بيانية، تكرار، جدول تعلم، استراحات.",
    proDe:["Wiederholung festigt Wissen","Multikanal ist effektiver","Überlernen hilft","Lernplan gibt Struktur"],
    proAr:["التكرار يثبت المعرفة","متعدد القنوات أكثر فعالية","التعلم الزائد يساعد","جدول التعلم يعطي هيكلاً"],
    contraDe:["Überlernen kann übertreiben","Nicht jede Methode passt jedem","Braucht Disziplin","Stille nicht immer verfügbar"],
    contraAr:["التعلم الزائد قد يبالغ","ليس كل طريقة تناسب الجميع","يحتاج انضباطاً","الهدوء التام ليس متاحاً دائماً"],
    vocab:[{de:"die Wiederholung",ar:"التكرار"},{de:"der Lernerfolg",ar:"نجاح التعلم"},{de:"die Methode",ar:"الطريقة"},{de:"das Zeitmanagement",ar:"إدارة الوقت"},{de:"der Lernstoff",ar:"مادة التعلم"},{de:"das Diagramm",ar:"الرسم البياني"}],
    phrasesDe:["Regelmäßige Wiederholung ist der Schlüssel zum Erfolg.","Je mehr Sinne, desto besser lernt man.","Pausen sind genauso wichtig wie das Lernen."],
    phrasesAr:["التكرار المنتظم هو مفتاح النجاح.","كلما زادت الحواس، كلما تعلمت أفضل.","الاستراحات مهمة بقدر التعلم."],
    problem:{titleDe:"Hochzeitsüberraschung organisieren",titleAr:"تنظيم مفاجأة زفاف",textDe:"Ihr Freund wird heiraten. Planen Sie eine Überraschung.",textAr:"صديقكما سيتزوج. خططوا لمفاجأة."},
    problemIdeasDe:["Überraschungsparty","Gemeinsames Geschenk","Rede vorbereiten","Freunde heimlich einladen","Video mit Glückwünschen","Essen und Dekoration"],
    problemIdeasAr:["حفلة مفاجئة","هدية مشتركة","تحضير خطاب","دعوة الأصدقاء سراً","فيديو بتهاني","الطعام والديكور"]},
  {id:28,icon:"🍺",
    titleDe:"Convenience Food",titleAr:"الطعام المريح (الوجبات الجاهزة)",
    textDe:"Convenience Food spart Zeit. Aber: viel Salz, Zucker, Fett. Führt zu Übergewicht und Verlust von Kochkenntnissen.",
    textAr:"الوجبات الجاهزة توفر وقتاً. لكن: كثير ملح، سكر، دهون. تؤدي للسمنة وفقدان مهارات الطبخ.",
    proDe:["Spart Zeit","Gleichbleibende Qualität","Saisonunabhängig","Einfach und bequem"],
    proAr:["يوفر الوقت","جودة ثابتة","مستقل عن الموسم","بسيط ومريح"],
    contraDe:["Verlust von Kochkenntnissen","Viel Zucker/Fett/Salz","Nährstoffverlust","Mehr Müll"],
    contraAr:["فقدان مهارات الطبخ","كثير سكر/دهون/ملح","فقدان العناصر الغذائية","يزيد النفايات"],
    vocab:[{de:"das Convenience Food",ar:"الطعام المريح"},{de:"das Fertigprodukt",ar:"المنتج الجاهز"},{de:"der Nährstoff",ar:"العنصر الغذائي"},{de:"das Übergewicht",ar:"زيادة الوزن"},{de:"die Zivilisationskrankheit",ar:"مرض الحضارة"},{de:"die Kochkenntnisse",ar:"مهارات الطبخ"}],
    phrasesDe:["Convenience Food ist praktisch, aber ungesund.","Selber kochen ist die bessere Wahl.","Bequemlichkeit sollte nicht auf Kosten der Gesundheit gehen."],
    phrasesAr:["الطعام المريح عملي لكنه غير صحي.","الطبخ المنزلي هو الخيار الأفضل.","الراحة لا يجب أن تكون على حساب الصحة."],
    problem:{titleDe:"Wohltätigkeitstheater",titleAr:"مسرحية خيرية",textDe:"Organisieren Sie ein Theaterstück und spenden Sie den Gewinn.",textAr:"نظموا مسرحية وتبرعوا بالربح للجمعيات الخيرية."},
    problemIdeasDe:["Stück auswählen","Proben und Rollen verteilen","Raum buchen","Karten verkaufen","Werbung","Wohltätigkeitsorganisation auswählen"],
    problemIdeasAr:["اختيار مسرحية","بروفات وتوزيع أدوار","حجز قاعة","بيع تذاكر","إعلان","اختيار جمعية خيرية"]},
  {id:29,icon:"📄",
    titleDe:"Darf man Fundsachen behalten?",titleAr:"هل يجوز الاحتفاظ بما تجد؟",
    textDe:"Ein Paar wurde verurteilt, weil es einen gefundenen Lottoschein einlöste. Der Finder muss den Eigentümer suchen. In den meisten Ländern gibt es Finderlohn. Kleingeld ist erlaubt.",
    textAr:"زوجان حوكما لأنهما صرفا تذكرة يانصيب وجداها. الباحث يجب أن يبحث عن المالك. في معظم البلدان مكافأة للباحث. النقود الصغيرة مسموح بها.",
    proDe:["Ehrlichkeit wird belohnt","Rückgabe von Fundsachen","Finderlohn ist geregelt","Kleingeld unproblematisch"],
    proAr:["الصدق يكافأ","إعادة الأشياء المفقودة","المكافأة منظمة قانونياً","النقود الصغيرة غير مشكلة"],
    contraDe:["Manche behalten illegal","Fundbüro ineffektiv","Große Beträge verlockend","Rechtliche Konsequenzen"],
    contraAr:["البعض يحتفظ بطريقة غير قانونية","مكتب المفقودات غير فعال","المبالغ الكبيرة تغري","عواقب قانونية"],
    vocab:[{de:"der Fund",ar:"الشيء الموجود"},{de:"der Finder",ar:"الباحث"},{de:"der Eigentümer",ar:"المالك"},{de:"das Fundbüro",ar:"مكتب المفقودات"},{de:"der Finderlohn",ar:"مكافأة الباحث"},{de:"der Lottoschein",ar:"تذكرة اليانصيب"},{de:"die Haftstrafe",ar:"عقوبة السجن"}],
    phrasesDe:["Man sollte versuchen, den Eigentümer zu finden.","Ehrlichkeit ist die beste Politik.","Bei großen Beträgen kann es illegal sein."],
    phrasesAr:["يجب محاولة إيجاد المالك.","الصدق أفضل سياسة.","في المبالغ الكبيرة قد يكون غير قانوني."],
    problem:{titleDe:"Freund mit Beinbruch aufmuntern",titleAr:"تشجيع صديق بكسر in الساق",textDe:"Ihr Freund Valentin hat sich das Bein gebrochen und langweilt sich im Krankenhaus.",textAr:"صديقك فالنتين كسر ساقه ويشعر بالملل in المستشفى."},
    problemIdeasDe:["Täglich besuchen","Bücher/Rätsel mitbringen","Filme/Serien schauen","Spiele spielen","Kleine Geschenke","Besuche von Freunden organisieren"],
    problemIdeasAr:["زيارته يومياً","إحضار كتب/ألغاز","مشاهدة أفلام/مسلسلات","لعب ألعاب","هدايا صغيرة","تنظيم زيارات الأصدقاء"]},
  {id:30,icon:"📝",
    titleDe:"Hausaufgaben – unnötig oder unvermeidbar?",titleAr:"الواجبات المنزلية – غير ضرورية أم لا مفر منها؟",
    textDe:"Gegner: mangelnde Chancengleichheit, Überlastung. Befürworter: Wiederholung festigt Wissen, fördert Selbstdisziplin.",
    textAr:"المعارضون: قلة تكافؤ الفرص، إرهاق. المؤيدون: التكرار يثبت المعرفة، يشجع الانضباط الذاتي.",
    proDe:["Wiederholung festigt Wissen","Fördert Selbstdisziplin","Bereitet auf das Leben vor","Selbstständiges Lernen"],
    proAr:["التكرار يثبت المعرفة","يشجع الانضباط الذاتي","يحضر للحياة","تعلم مستقل"],
    contraDe:["Mangelnde Chancengleichheit","Überlastung nach der Schule","Nicht alle bekommen Hilfe","Lerneffekt bei Müdigkeit fraglich"],
    contraAr:["قلة تكافؤ الفرص","إرهاق بعد المدرسة","ليس الجميع يحصل على مساعدة","تأثير التعلم مشكوك فيه عند الإرهاق"],
    vocab:[{de:"die Hausaufgabe",ar:"الواجب المنزلي"},{de:"die Selbstdisziplin",ar:"الانضباط الذاتي"},{de:"die Chancengleichheit",ar:"تكافؤ الفرص"},{de:"die Überlastung",ar:"الإرهاق"},{de:"die Selbstständigkeit",ar:"الاستقلالية"}],
    phrasesDe:["Hausaufgaben sind wichtig für die Vertiefung.","Qualität ist wichtiger als Quantität.","Das richtige Maß ist der Schlüssel."],
    phrasesAr:["الواجبات المنزلية مهمة للتعمق.","الجودة أهم من الكمية.","الكمية المعتدلة هي المفتاح."],
    problem:{titleDe:"Kochparty im Deutschkurs",titleAr:"حفلة طبخ in دورة الألمانية",textDe:"Organisieren Sie eine Kochparty im Deutschkurs.",textAr:"نظموا حفلة طبخ in دورة الألمانية."},
    problemIdeasDe:["Gerichte aus verschiedenen Ländern kochen","Aufgaben verteilen","Rezepte auf Deutsch lesen","Gemeinsam essen","Musik und Spiele","Kosten teilen"],
    problemIdeasAr:["طبخ أطباق من بلدان مختلفة","توزيع المهام","قراءة وصفات بالألمانية","الأكل معاً","موسيقى وألعاب","تقسيم التكاليف"]},
  {id:31,icon:"🏣",
    titleDe:"Wohnung in der Stadt oder Haus auf dem Land?",titleAr:"شقة in المدينة أم منزل in الريف؟",
    textDe:"Stadt: kurze Wege, Kultur. Land: Platz, Ruhe. Probleme: Zersiedelung, zunehmender Verkehr. Beides hat Vor- und Nachteile.",
    textAr:"المدينة: مسافات قصيرة، ثقافة. الريف: مساحة، هدوء. مشاكل: التوسع العمراني، زيادة المرور. لكل مزايا وعيوب.",
    proDe:["Stadt: kurze Wege, Kultur","Land: viel Platz, Garten","Stadt: kein Auto nötig","Land: Ruhe und Natur"],
    proAr:["المدينة: مسافات قصيرة، ثقافة","الريف: مساحة كبيرة، حديقة","المدينة: لا حاجة لسيارة","الريف: هدوء وطبيعة"],
    contraDe:["Stadt: laut, teuer","Land: lange Wege","Stadt: kleine Wohnungen","Land: Zersiedelung"],
    contraAr:["المدينة: صاخبة، غالية","الريف: مسافات طويلة","المدينة: شقق صغيرة","الريف: توسع عمراني"],
    vocab:[{de:"die Stadtwohnung",ar:"شقة in المدينة"},{de:"das Haus im Grünen",ar:"منزل in الريف"},{de:"die Zersiedelung",ar:"التوسع العمراني"},{de:"die Umweltbelastung",ar:"التلوث البيئي"},{de:"die Idylle",ar:"المثالية"},{de:"die Lebensqualität",ar:"جودة الحياة"}],
    phrasesDe:["Die Stadt bietet kurze Wege und Kultur.","Ein Haus auf dem Land ist ruhiger.","Das hängt von der persönlichen Lebenssituation ab."],
    phrasesAr:["المدينة توفر مسافات قصيرة وثقافة.","المنزل in الريف أكثر هدوءاً.","يعتمد على وضع الحياة الشخصي."],
    problem:{titleDe:"Kursraum gemütlicher machen",titleAr:"جعل قاعة الدورة أكثر وداً",textDe:"Die Kursleiterin möchte den Kursraum gemütlicher machen.",textAr:"معلمة الدورة تريد جعل القاعة أكثر وداً."},
    problemIdeasDe:["Pflanzen aufstellen","Plakate an die Wände","Bessere Beleuchtung","Gemütliche Leseecke","Hintergrundmusik","Aufgaben verteilen"],
    problemIdeasAr:["وضع نباتات","ملصقات على الجدران","إضاءة أفضل","ركن قراءة مريح","موسيقى in الخلفية","توزيع المهام"]},
  {id:32,icon:"📱",
    titleDe:"Kinder unterschätzen Handy- und Internetrisiken",titleAr:"الأطفال يستهينون بمخاطر الهاتف والإنترنت",
    textDe:"75% der 9-10-Jährigen haben ein Handy. Risiken sind bekannt, aber Kinder erzählen Eltern nur in schweren Fällen. Risiken: Cybermobbing, Gewalt, Pornografie.",
    textAr:"75% من الأطفال 9-10 سنوات لديهم هاتف. المخاطر معروفة لكن الأطفال لا يخبرون الآباء إلا in الحالات الخطيرة. مخاطر: تنمر إلكتروني، عنف، إباحية.",
    proDe:["Handy ist heute normal","Lernen Medienkompetenz","Eltern können erreichen","Zugang zu Informationen"],
    proAr:["الهاتف طبيعي اليوم","يتعلمون الثقافة الإعلامية","الآباء يمكنهم الوصول","وصول للمعلومات"],
    contraDe:["Risiken werden unterschätzt","Cybermobbing","Unangemessene Inhalte","Kein Vertrauen zu Eltern"],
    contraAr:["المخاطر يستهان بها","التنمر الإلكتروني","محتوى غير مناسب","لا ثقة in الآباء"],
    vocab:[{de:"das Handy",ar:"الهاتف المحمول"},{de:"der Missbrauch",ar:"إساءة الاستخدام"},{de:"das Cybermobbing",ar:"التنمر الإلكتروني"},{de:"die Drohung",ar:"التهديد"},{de:"die Erpressung",ar:"الابتزاز"},{de:"der Jugendschutz",ar:"حماية الشباب"}],
    phrasesDe:["Kinder brauchen Begleitung bei der Mediennutzung.","Eltern sollten über Risiken sprechen.","Medienkompetenz sollte in der Schule gelehrt werden."],
    phrasesAr:["الأطفال بحاجة لمرافقة in استخدام الوسائط.","يجب على الآباء التحدث عن المخاطر.","الثقافة الإعلامية يجب أن تدرس in المدرسة."],
    problem:{titleDe:"Geburtstagsparty für Kursteilnehmer",titleAr:"حفلة عيد ميلاد لمشارك in الدورة",textDe:"Ein Sprachkursteilnehmer hat Geburtstag.",textAr:"أحد المشاركين in دورة اللغة له عيد ميلاد."},
    problemIdeasDe:["Gemeinsames Geschenk","Kuchen oder Essen","Raum dekorieren","Überraschungsparty","Musik und Spiele","Karte mit persönlichen Wünschen"],
    problemIdeasAr:["هدية مشتركة","كعكة أو طعام","تزيين القاعة","حفلة مفاجئة","موسيقى وألعاب","بطاقة بأمنيات شخصية"]},
  {id:33,icon:"🌐",
    titleDe:"Eine Woche ohne Internet",titleAr:"أسبوع بدون إنترنت",
    textDe:"Experiment: eine Woche ohne Internet. Manches dauert länger, Kommunikation ist schwieriger. Fazit: Internet verbindet Menschen.",
    textAr:"تجربة: أسبوع بدون إنترنت. بعض الأمور تأخذ وقتاً أطول، التواصل أصعب. خلاصة: الإنترنت يربط الناس.",
    proDe:["Weniger Ablenkung","Mehr Zeit für Aktivitäten","Bewusste Nutzung","Entschleunigung"],
    proAr:["تشويش أقل","وقت أكثر للأنشطة","استخدام واعٍ","إبطاء الحياة"],
    contraDe:["Vieles wird schwieriger","Langsame Kommunikation","Verpasst Informationen","Heute nicht möglich"],
    contraAr:["أمور كثيرة تصبح أصعب","التواصل بطيء","يفوتك معلومات","غير ممكن اليوم"],
    vocab:[{de:"die Ablenkung",ar:"التشتت"},{de:"der Stadtplan",ar:"خريطة المدينة"},{de:"die Kommunikation",ar:"التواصل"},{de:"der Verzicht",ar:"التخلي"},{de:"das Experiment",ar:"التجربة"}],
    phrasesDe:["Eine Woche ohne Internet ist ein spannendes Experiment.","Man merkt, wie abhängig man ist.","Das Internet ist heute nicht mehr wegzudenken."],
    phrasesAr:["أسبوع بدون إنترنت تجربة مثيرة.","تدرك كم أنت معتمد عليه.","الإنترنت لا يمكن الاستغناء عنه اليوم."],
    problem:{titleDe:"Vortrag über Fremdsprachenlernen",titleAr:"عرض عن تعلم اللغات الأجنبية",textDe:"Sie wurden eingeladen, in einer Schule über die Bedeutung des Fremdsprachenlernens zu sprechen.",textAr:"دُعيت للتحدث in مدرسة عن أهمية تعلم اللغات الأجنبية."},
    problemIdeasDe:["Vorteile nennen","Persönliche Erfahrungen","Lerntipps geben","Interaktive Übungen","Fragen beantworten","Handouts mit Tipps"],
    problemIdeasAr:["ذكر المزايا","تجارب شخصية","نصائح للتعلم","تمارين تفاعلية","الإجابة على الأسئلة","نشرات بنصائح"]},
  {id:34,icon:"💻",
    titleDe:"Digitale Unterrichtsmaterialien",titleAr:"مواد تعليمية رقمية",
    textDe:"E-Books in Schulen? Befürworter: modern, Multimedia, Medienkompetenz. Gegner: Finanzierung unsicher, Wirkungen unerforscht.",
    textAr:"الكتب الإلكترونية in المدارس؟ المؤيدون: حديثة، وسائط متعددة، ثقافة إعلامية. المعارضون: تمويل غير مؤكد، آثار غير مدروسة.",
    proDe:["Moderne Inhalte","Multimedia-Funktionen","Fördert Medienkompetenz","Weniger Gewicht"],
    proAr:["محتوى حديث","وظائف وسائط متعددة","يشجع الثقافة الإعلامية","وزن أقل"],
    contraDe:["Hohe Kosten","Wirkungen unerforscht","Ablenkung","Technische Probleme"],
    contraAr:["تكاليف عالية","التأثيرات غير مدروسة","تشتت","مشاكل تقنية"],
    vocab:[{de:"das digitale Unterrichtsmaterial",ar:"مواد تعليمية رقمية"},{de:"das E-Book",ar:"الكتاب الإلكتروني"},{de:"die Digitalisierung",ar:"الرقمنة"},{de:"die Medienkompetenz",ar:"الثقافة الإعلامية"},{de:"die Finanzierung",ar:"التمويل"}],
    phrasesDe:["Digitale Bücher haben viele Vorteile.","Aber sie sind teuer.","Eine Mischung aus digital und gedruckt ist ideal."],
    phrasesAr:["الكتب الرقمية لها مزايا كثيرة.","لكنها غالية الثمن.","مزيج من الرقمي والمطبوع مثالي."],
    problem:{titleDe:"Flohmarkt organisieren",titleAr:"تنظيم سوق للسلع المستعملة",textDe:"Im Frühjahr möchten Sie einen Flohmarkt organisieren.",textAr:"in بداية الربيع تريد تنظيم سوق للسلع المستعملة."},
    problemIdeasDe:["Datum und Ort","Nachbarn einladen","Tische organisieren","Werbung","Kaffeestand","Spenden des Gewinns"],
    problemIdeasAr:["تاريخ ومكان","دعوة الجيران","تنظيم الطاولات","إعلان","ركن قهوة","التبرع بالربح"]},
  {id:35,icon:"🏆",
    titleDe:"Spezialschulen für Hochbegabte",titleAr:"مدارس خاصة للموهوبين",
    textDe:"Separation oder Integration? Spezialschulen: gezielte Förderung. Integration: ganzheitliche Entwicklung. Beides hat Vor- und Nachteile.",
    textAr:"فصل أم دمج؟ المدارس الخاصة: دعم موجه. الدمج: تطور شامل. لكل مزايا وعيوب.",
    proDe:["Gezielte Förderung","Austausch mit Gleichen","Spezielle Angebote","Schnellere Fortschritte"],
    proAr:["دعم موجه","تبادل مع المماثلين","عروض خاصة","تقدم أسرع"],
    contraDe:["Soziale Ausgrenzung","Einseitige Förderung","Mangelnde Integration","Stigma (hochbegabt)"],
    contraAr:["استبعاد اجتماعي","دعم أحادي الجانب","اندماج ناقص","وصف (موهوب)"],
    vocab:[{de:"hochbegabt",ar:"موهوب جداً"},{de:"die Förderung",ar:"الدعم"},{de:"die Integration",ar:"الدمج"},{de:"die Separation",ar:"الفصل"},{de:"die Begabung",ar:"الموهبة"},{de:"das Potenzial",ar:"الإمكانات"}],
    phrasesDe:["Hochbegabte brauchen besondere Förderung.","Integration ist auch wichtig.","Jedes Kind ist anders."],
    phrasesAr:["الموهوبون بحاجة لدعم خاص.","الدمج مهم أيضاً.","كل طفل مختلف."],
    problem:{titleDe:"Kinobesuch am letzten Kurstag",titleAr:"زيارة سينما in آخر يوم دورة",textDe:"Am letzten Tag des Deutschkurses wollen alle ins Kino.",textAr:"آخر يوم in دورة الألمانية، الجميع يريد الذهاب للسينما."},
    problemIdeasDe:["Kinoprogramm prüfen","Film auf Deutsch aussuchen","Gemeinsam Tickets buchen","Essen vor dem Kino","Kleine Party planen","Alle einladen"],
    problemIdeasAr:["مراجعة برنامج السينما","اختيار فيلم بالألمانية","حجز تذاكر معاً","الأكل قبل السينما","تخطيط حفلة صغيرة","دعوة الجميع"]},
  {id:36,icon:"🏦",
    titleDe:"Sparkonto für Kinder",titleAr:"حساب ادخار للأطفال",
    textDe:"Früher Spardose, heute Kinderkonten, Festgelder, ETF-Sparpläne. Finanztest empfiehlt Indexfonds ab 25 Euro monatlich.",
    textAr:"سابقاً حصالة، اليوم حسابات أطفال، ودائع ثابتة، خطط ادخار ETF. Finanztest توصي بصناديق مؤشرات من 25 يورو شهرياً.",
    proDe:["Finanzielle Vorsorge für Kinder","Zinseszinseffekt","Fördert Sparverhalten"],
    proAr:["ادخار مالي للأطفال","فائدة الفائدة المركبة","يشجع عادة الادخار"],
    contraDe:["Niedrige Zinsen","Komplexe Produkte","Risiken bei ETFs"],
    contraAr:["فوائد منخفضة","منتجات معقدة","مخاطر in ETFs"],
    vocab:[{de:"das Sparkonto",ar:"حساب التوفير"},{de:"die Verzinsung",ar:"الفائدة"},{de:"der ETF-Sparplan",ar:"خطة ادخار ETF"},{de:"die Geldanlage",ar:"الاستثمار"},{de:"die Rendite",ar:"العائد"},{de:"der Indexfonds",ar:"صندوق المؤشرات"}],
    phrasesDe:["Sparen für Kinder ist eine gute Idee.","ETF-Sparpläne sind für Anfänger geeignet.","Finanzbildung sollte in der Schule beginnen."],
    phrasesAr:["الادخار للأطفال فكرة جيدة.","خطط ETF مناسبة للمبتدئين.","التثقيف المالي يجب أن يبدأ in المدرسة."],
    problem:{titleDe:"Bücherspende für die Bibliothek",titleAr:"تبرع بالكتب للمكتبة",textDe:"Organisieren Sie eine Bücherspendenaktion für die örtliche Bibliothek.",textAr:"تنظيم حدث لجمع التبرعات من الكتب للمكتبة المحلية."},
    problemIdeasDe:["Sammelaktion starten","Zur Spende aufrufen","Bücher sortieren","Bibliothek informieren","Freiwillige für Transport","Dankeskarten"],
    problemIdeasAr:["بدء حملة جمع","دعوة للتبرع","فرز الكتب","إعلام المكتبة","متطوعون للنقل","بطاقات شكر"]},
  {id:37,icon:"🐲",
    titleDe:"Tierversuche – Pro und Contra",titleAr:"تجارب الحيوانات – مؤيد ومعارض",
    textDe:"Tierversuche: medizinischer Fortschritt vs. Tierleid. Streng reguliert. Alternativen: künstliche Organe, Computersimulationen.",
    textAr:"تجارب الحيوانات: تقدم طبي vs. معاناة الحيوانات. منظمة بدقة. بدائل: أعضاء اصطناعية، محاكاة حاسوبية.",
    proDe:["Medizinischer Fortschritt","Lebensrettende Medikamente","Streng reguliert"],
    proAr:["تقدم طبي","أدوية منقذة للحياة","منظمة بدقة"],
    contraDe:["Tierleid","Unethisch","Nicht immer übertragbar","Alternativen vorhanden"],
    contraAr:["معاناة الحيوانات","غير أخلاقي","غير قابل للنقل دائماً","بدائل متوفرة"],
    vocab:[{de:"der Tierversuch",ar:"تجربة على الحيوانات"},{de:"das Versuchstier",ar:"حيوان التجارب"},{de:"die Grundlagenforschung",ar:"البحث الأساسي"},{de:"das Leid",ar:"المعاناة"},{de:"die Ethik",ar:"الأخلاق"},{de:"die Computersimulation",ar:"المحاكاة الحاسوبية"}],
    phrasesDe:["Tierversuche sind ein ethisches Dilemma.","Sie haben zu medizinischem Fortschritt geführt.","Man sollte mehr nach Alternativen forschen."],
    phrasesAr:["تجارب الحيوانات معضلة أخلاقية.","لقد أدت لتقدم طبي.","يجب البحث أكثر عن بدائل."],
    problem:{titleDe:"3-tägige Reise ans Meer",titleAr:"رحلة 3 أيام إلى البحر",textDe:"Mit den Kursteilnehmern ans Meer.",textAr:"مع مشاركي الدورة إلى البحر."},
    problemIdeasDe:["Ziel auswählen","Unterkunft buchen","Anreise organisieren","Aktivitäten am Strand","Verpflegung planen","Regenprogramm"],
    problemIdeasAr:["اختيار الوجهة","حجز الإقامة","تنظيم السفر","أنشطة على البحر","تخطيط الطعام","برنامج للمطر"]},
  {id:38,icon:"🏠",
    titleDe:"Hausfrau ein Leben lang?",titleAr:"ربة بيت مدى الحياة؟",
    textDe:"Heute eine bewusste Entscheidung. Befürworter: Zeit für Kinder. Gegner: finanzielle Abhängigkeit, verpasste Berufschancen.",
    textAr:"اليوم قرار واعٍ. المؤيدون: وقت للأطفال. المعارضون: تبعية مالية، فرص مهنية ضائعة.",
    proDe:["Zeit für die Familie","Wichtige Arbeit für die Gesellschaft","Alternativer Lebensstil","Kein Berufsstress"],
    proAr:["وقت للعائلة","عمل مهم للمجتمع","نمط حياة بديل","لا توتر مهني"],
    contraDe:["Finanzielle Abhängigkeit","Weniger Rente","Mangelnde Anerkennung","Verpasste Berufschancen"],
    contraAr:["تبعية مالية","معاش أقل","نقص التقدير","فرص مهنية ضائعة"],
    vocab:[{de:"die Hausfrau",ar:"ربة البيت"},{de:"der Haushalt",ar:"المنزل"},{de:"der Ernährer",ar:"المعيل"},{de:"die Anerkennung",ar:"التقدير"},{de:"die Karriere",ar:"المهنة"},{de:"die Rollenverteilung",ar:"توزيع الأدوار"}],
    phrasesDe:["Hausfrau zu sein ist eine persönliche Entscheidung.","Kinder profitieren von der Zeit der Eltern.","Jede Frau sollte selbst entscheiden."],
    phrasesAr:["أن تكون ربة بيت هو قرار شخصي.","الأطفال يستفيدون من وقت الوالدين.","كل امرأة يجب أن تقرر بنفسها."],
    problem:{titleDe:"Land im Kurs vorstellen",titleAr:"وصف بلد in الفصل",textDe:"Sie sollen ein Land vorstellen: Städte, Essen, Musik.",textAr:"يجب وصف بلد: المدن، الطعام، الموسيقى."},
    problemIdeasDe:["Land auswählen","Bekannte Städte","Traditionelles Essen","Musik und Gesang","Bilder zeigen","Präsentation vorbereiten"],
    problemIdeasAr:["اختيار بلد","مدن مشهورة","طعام تقليدي","موسيقى وغناء","عرض صور","تحضير عرض"]},
];
// ===== REDEMITTEL (Deutsch + Arabisch) =====
const REDEMITTEL = [
  {cat:"Meinung äußern",items:["Meiner Meinung nach ...","Ich bin überzeugt, dass ...","Ich finde/glaube, dass ...","Aus meiner Sicht ...","Meiner Ansicht nach ...","Ich sehe das so, dass ...","Dazu möchte ich sagen: ..."]},
  {cat:"Zustimmung / Ablehnung",items:["Da stimme ich zu.","Das sehe ich genauso.","Da bin ich anderer Meinung.","Das kann ich nicht ganz nachvollziehen.","Ich sehe das anders, weil ...","Da muss ich widersprechen.","Einerseits hast du recht, aber andererseits ..."]},
  {cat:"Argumente",items:["Ein Grund dafür/dagegen ist ...","Ein weiterer Vor-/Nachteil ist ...","Was dafür/dagegen spricht, ist ...","Man muss bedenken, dass ...","Ein wichtiges Argument ist ...","Man darf nicht vergessen, dass ...","Vor allem ist zu beachten, dass ..."]},
  {cat:"Beispiele nennen",items:["Zum Beispiel ...","Ein Beispiel dafür ist ...","Das zeigt sich zum Beispiel in ...","Wie man am Beispiel ... sehen kann."]},
  {cat:"Vorschläge machen",items:["Ich schlage vor, dass ...","Es besteht die Möglichkeit ...","Was hältst du von ...","Ich habe eine Idee: ...","Könnten wir nicht ...","Mein Vorschlag wäre ..."]},
  {cat:"Fragen / Reagieren",items:["Was ist deine Meinung dazu?","Wie siehst du das?","Kannst du das erklären?","Das ist ein guter Punkt.","Da hast du recht.","Gute Frage!"]},
  {cat:"Zusammenfassen",items:["Zusammenfassend kann man sagen ...","Im Großen und Ganzen ...","Abschließend möchte ich sagen ...","Fazit: ...","Alles in allem ..."]},
];
// ===== Arabic translations for Redemittel =====
const REDEMITTEL_AR = [
  {cat:"إبداء الرأي",items:["في رأيي ...","أنا مقتنع بأن ...","أجد/أعتقد أن ...","من وجهة نظري ...","حسب رأيي ...","أنا أرى أن ...","أود أن أقول بخصوص هذا: ..."]},
  {cat:"الموافقة / الرفض",items:["أوافقك الرأي.","أرى ذلك تماماً.","أنا رأيي مختلف.","لا أستطيع فهم ذلك تماماً.","أرى غير ذلك لأن ...","يجب أن أعترض هنا.","من ناحية أنت محق، لكن من ناحية أخرى ..."]},
  {cat:"الحجج",items:["سبب لذلك/ضد ذلك هو ...","ميزة/عيب آخر هو ...","مما يؤيد/يعارض ذلك ...","يجب مراعاة أن ...","حجة مهمة هي ...","لا يجب نسيان أن ...","قبل كل شيء يجب ملاحظة أن ..."]},
  {cat:"ذكر أمثلة",items:["على سبيل المثال ...","مثال على ذلك هو ...","يظهر ذلك مثلاً في ...","كما يمكن رؤيته في مثال ..."]},
  {cat:"تقديم اقتراحات",items:["أقترح أن ...","هناك إمكانية ...","ما رأيك في ...","لدي فكرة: ...","هل يمكننا ...","اقتراحي هو ..."]},
  {cat:"السؤال / الرد",items:["ما رأيك في ذلك؟","كيف ترى ذلك؟","هل يمكنك شرح ذلك؟","هذه نقطة جيدة.","أنت محق.","سؤال جيد!"]},
  {cat:"التلخيص",items:["خلاصة القول ...","بشكل عام ...","في الختام أود أن أقول ...","الخلاصة: ...","في المجمل ..."]},
];
